### ISSUE TITLE
Support Power Model Dynamic update

### ISSUE THREAD

**Issue by marceloamaral** [sustainable-computing-io/kepler#1016]
### What would you like to be added?

Currently, when Kepler is configured with trained Power Model, it attempts to load the model that corresponds to the host CPU. VMs generally expose the host CPU, and in cases where a VM is migrated to a different host, the host CPU might change.

### Why is this needed?

In such scenarios, there may be a need to dynamic update the trained power model.

Even if Kepler is using a general power model due to the absence of a specific model for the given CPU model, migration could potentially move Kepler to a node where the model is available. In such cases, Kepler should also be prepared to update its power model.

**Comment by jichenjc** [comment]
is the calculation comes from per kepler level so if each node has its own kepler running and it need calculate the VM after the live migration??
