### ISSUE TITLE
Libbpf failed to get metric after the first collection.

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler#1057]
### What happened?

Libbpf can collect the metric at the first collection; however, it doesn't get any metric after that.
The reason is that there is a bug when ebpfBatchGetAndDelete set to False.

From log, we found that ebpfBatchGetAndDelete is set to False when got an error. 
```
I1116 01:51:46.292107   11020 libbpf_attacher.go:356] GetValueAndDeleteBatch failed: failed to batch lookup and delete values 0xc00043c000 in map processes: ret -22 (err: invalid argument). A partial value might have been collected.
```

The problem is the following logic where `libbpfCollectProcessSingleHash` will never be called. 

https://github.com/sustainable-computing-io/kepler/blob/5cb98b5dd3e7d1f448a5eee3775b4becc3c56c65/pkg/bpfassets/attacher/libbpf_attacher.go#L211 

I confirm the fix after change.
![Screenshot 2023-11-16 at 14 24 50](https://github.com/sustainable-computing-io/kepler/assets/11749848/d633d529-7a73-4fb3-acc8-5b479d817c54)

### What did you expect to happen?

libbpfCollectProcessSingleHash should be called if ebpfBatchGetAndDelete is False.

### How can we reproduce it (as minimally and precisely as possible)?

Run on the system that failed to execute GetValueAndDeleteBatch without error. 

### Kepler image tag

<details>

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider or bare metal

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jichenjc** [comment]
code merged , I believe we can close it now
