### ISSUE TITLE
CPU architecture by Node is reported as "unknown" for AMD CPUs

### ISSUE THREAD

**Issue by BGrasnick** [sustainable-computing-io/kepler#1066]
### What happened?

In the Power Monitoring / Overview in OpenShift when deploying via the kepler-operator the CPU architecture is reported as unknown for AMD CPUs.

### What did you expect to happen?

Report AMD Zen / AMD Zen 2 / AMD Zen 3 for respective AMD CPUs

### How can we reproduce it (as minimally and precisely as possible)?

Deploy kepler via kepler-operator on an OpenShift cluster that uses at least one node with a AMD CPU (e.g. m6a, r5a or c5a instance types in AWS)

### Kepler image tag

<details>
release-0.6.1-libbpf
</details>

### Kubernetes version

<details>
```console
$ kubectl version
# paste output here
```
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.16+ec2a592", GitCommit:"d328604e81077de3864c29da77f8a7f07e2b6a77", GitTreeState:"clean", BuildDate:"2023-10-14T01:09:12Z", GoVersion:"go1.18.10 X:strictfipsruntime", Compiler:"gc", Platform:"linux/amd64
</details>
=> OpenShift 4.11

### Cloud provider or bare metal

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by rootfs** [comment]
@BGrasnick what result do you get when running `cpuid` on your host?
