### ISSUE TITLE
[RFC] Build multiple-arch base, builder and kepler image

### ISSUE THREAD

**Issue by huoqifeng** [sustainable-computing-io/kepler#1099]
# What would you like to be added?

Kepler does not have s390x `base`, `builder` and `kepler` image available yet.

# Why is this needed?

As we're adding the s390x(IBM System Z) support in function level in https://github.com/sustainable-computing-io/kepler/pull/1030, it's time to consider to build the `base`, `builder` and `kepler` image as multi-arch images.

# Approach
As obviously the contents in all of the images are different per architecture. 

## Option 1: architecture specific Dockerfile
I think it's reasonable to use following files to track architecture specific Dockerfile, like:
```
Dockerfile.bcc.base.amd64 
Dockerfile.bcc.base.s390x
Dockerfile.bcc.base.arm64
...
Dockerfile.bcc.builder.amd64 
Dockerfile.bcc.builder.s390x
Dockerfile.bcc.builder.arm64
...
Dockerfile.bcc.kepler.amd64 
Dockerfile.bcc.kepler.s390x
Dockerfile.bcc.kepler.arm64
```
We can build architecture specific image and then create the multi-arch images manifest after all arch specific images built/push. Like:
```
docker buildx imagetools create -t "${manifest}" "${arch_images[@]}"
```

## Option 2: architecture specific install scripts
Alternative is to consider to add a `install_base_packages.sh` file to handle multiple architectures packages installation in a single Dockerfile file. For example, Using a single Docker file like:
```
Dockerfile.bcc.base
```
In the Dockerfile.bcc.base will call
```
RUN ./install_base_packages.sh
```
We handle architecture specific algorithm in the file install_base_packages.sh
In file `install_base_packages.sh` we can do like:
```
arch=$(uname -m)

if s390x
    handle s390 packages
fi

if amd64
    handle amd64 packages
fi
```
In this approach, we can use a single buildx command build all architectures images and corresponding manifest. Like:
```
docker buildx build --platform "${supported_arches}" -f Dockerfile.bcc.base
```

Similar approach could be done for `Dockerfile.bcc.builder` and `Dockerfile.bcc.kepler`.

I'm raising this RFC to discuss the approach...

**Comment by huoqifeng** [comment]
@rootfs @SamYuan1990 @jichenjc @jiangphcn Idea?

**Comment by SamYuan1990** [comment]
> @rootfs @SamYuan1990 @jichenjc @jiangphcn Idea?

I hope we can have a no GPU based image. Hence or so that, we can have a ubi based image and support all platform without GPU, for example edge computing usage.

btw, @huoqifeng , we are plan to replace bcc by libbpf as ebpf libraray.

**Comment by rootfs** [comment]
yes, get a no gpu image is fine to me. @vimalk78 is also refactoring the base image, lets sync on the base image and support matrices in the community meeting

**Comment by SamYuan1990** [comment]
> yes, get a no gpu image is fine to me. @vimalk78 is also refactoring the base image, lets sync on the base image and support matrices in the community meeting

I will try to attend it tomorrow night my local time. I may have some personal conflicts.

**Comment by huoqifeng** [comment]
I'm going to close the issue as which was resolved partially by https://github.com/sustainable-computing-io/kepler/pull/1103
