### ISSUE TITLE
contradicting Grafana curves

### ISSUE THREAD

**Issue by jochen-schuettler** [sustainable-computing-io/kepler#1100]
### What happened?

The consumption curve in kWh shows several large steps between 12 and 1 p.m. The consumption curve in W shows peaks only at one time roughly 12:30.
![grafik](https://github.com/sustainable-computing-io/kepler/assets/115154710/7904217d-5757-43bc-9484-38b7534fa1f4)

### What did you expect to happen?

Either there is one kWh step at the same time as the peak in W, or there must be several peaks in W at the times when there are steps in kWh.

### How can we reproduce it (as minimally and precisely as possible)?

I have no idea.

### Kepler image tag

<details>
0.6.1
</details>

### Kubernetes version

<details>
1.24
</details>

### Cloud provider or bare metal

<details>
AWS EKS / ECS
</details>

### OS version

<details>
Amazon Linux 2
</details>

### Install tools

<details>
Helm
</details>

### Kepler deployment config

<details>
unchanged from given Helm chart
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI Version: v1.12.0-eksbuild.2
CSI Version: v1.14.0-eksbuild.1
</details>

**Comment by jochen-schuettler** [comment]
Due to illness, no additional info, but another strange curve:
![image](https://github.com/sustainable-computing-io/kepler/assets/115154710/e19c2422-3d75-43bd-9003-77057ac301fa)
It looks as if the consumption is decreasing in the end. How is that possible?

**Comment by rootfs** [comment]
not sure about the first issue, but for the 2nd (i.e. decreasing curve), since it is on a 24 hour period basis (i.e. not accumulative) the drop makes sense.

**Comment by jochen-schuettler** [comment]
I deleted the 2nd non-issue. Do you have any ideas how to gain more info on the repeating problem?

**Comment by jochen-schuettler** [comment]
I updated the Details now

**Comment by jochen-schuettler** [comment]
An idea: If the kWh-curve is smoothed by an averaging filter, that could explain the behaviour. Is that the case?

**Comment by marceloamaral** [comment]
Yes, KWh extrapolates the average values over a longer interval.
