### ISSUE TITLE
Unit test problem in the CI

### ISSUE THREAD

**Issue by marceloamaral** [sustainable-computing-io/kepler#1129]
### What happened?

The PR #1097 changed how the libbpf is installed, but because of that the unit test in the CI is failing

<img width="1121" alt="Screenshot 2023-12-15 at 23 44 32" src="https://github.com/sustainable-computing-io/kepler/assets/5133121/b1423ee0-8515-469e-8196-33c7dca9efe5">

### What did you expect to happen?

Unit test in Ci should work

### How can we reproduce it (as minimally and precisely as possible)?

See: 
https://github.com/sustainable-computing-io/kepler/actions/runs/7223414090/job/19682423008?pr=1089#step:7:14

### Kepler image tag

<details>

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider or bare metal

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SamYuan1990** [comment]
hi @marceloamaral as #1089 been merged, is this issue still avaliable?

**Comment by marceloamaral** [comment]
@SamYuan1990 looks like it was fixed.
