### ISSUE TITLE
Kepler release-0.7.3 reporting higher kepler_container_joules_total values on BM

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/kepler#1228]
### What happened?

When Kepler using `release-0.7.3` deployed on OCP 4.14(BM) it shows energy reading on the higher side. Comparing it with `release-0.7.2` there is a huge difference in metric readings

![Screenshot 2024-02-13 at 4 48 47 PM](https://github.com/sustainable-computing-io/kepler/assets/115542213/adfd0827-393b-4c40-8238-2d825409203c)

![Screenshot 2024-02-13 at 5 01 56 PM](https://github.com/sustainable-computing-io/kepler/assets/115542213/5847cc24-9f68-4079-9766-a30b7e6f3a61)

### What did you expect to happen?

There shouldn't be a huge difference in terms of energy reading provided by Kepler in the case of BM

### How can we reproduce it (as minimally and precisely as possible)?

Deploy Kepler with `release-0.7.3` and `release-0.7.2` on OCP BM cluster and compare metric values

### Anything else we need to know?

[kepler-new.log](https://github.com/sustainable-computing-io/kepler/files/14260921/kepler-new.log)
[kepler-old.log](https://github.com/sustainable-computing-io/kepler/files/14260922/kepler-old.log)

[kepler-new-cm.json](https://github.com/sustainable-computing-io/kepler/files/14261086/kepler-new-cm.json)
[kepler-new-ds.json](https://github.com/sustainable-computing-io/kepler/files/14261088/kepler-new-ds.json)
[kepler-old-cm.json](https://github.com/sustainable-computing-io/kepler/files/14261089/kepler-old-cm.json)
[kepler-old-ds.json](https://github.com/sustainable-computing-io/kepler/files/14261090/kepler-old-ds.json)

### Kepler image tag

<details>
`release-0.7.3`
</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider or bare metal

<details>
Bare Metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by rootfs** [comment]
`kepler_container_package_joules_total` matches the readings on my laptop, but `kepler_container_joules_total` is wrong. 

@marceloamaral can you take a look? this is the release with the refactoring
