### ISSUE TITLE
Update installation manifests to include a serviceaccount access token secret 

### ISSUE THREAD

**Issue by sallyom** [sustainable-computing-io/kepler#127]
**Describe the bug**
Manifests for deploying kepler require an update wrt the grafana serviceaccount access tokens. 
As of latest kube version, serviceaccounts no longer automatically generate access tokens. Now a token secret is required. I'll submit an update. 

https://docs.openshift.com/container-platform/4.11/authentication/using-service-accounts-in-applications.html#auto-generated-sa-token-secrets_using-service-accounts

**Comment by rootfs** [comment]
refer to #126

**Comment by rootfs** [comment]
@williamcaban

**Comment by sallyom** [comment]
I'll close this one in favor of https://github.com/sustainable-computing-io/kepler/issues/126! I looked but didn't see that one :)
