### ISSUE TITLE
panic: inconsistent label cardinality: expected 21 label values but got 20

### ISSUE THREAD

**Issue by jichenjc** [sustainable-computing-io/kepler#131]
**Describe the bug**

follow https://github.com/sustainable-computing-io/kepler

after `~/kube-prometheus# kubectl apply -f manifests/`, saw this error

seems something inconsistent ..
```
panic: inconsistent label cardinality: expected 21 label values but got 20 in []string{"system_processes", "system", "containerd", "388246", "2674068", "0", "0", "0", "0", "0", "0", "3", "151", "17428480", "1070764032", "0", "0", "0", "0", "0"}

goroutine 101 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
        /opt/app-root/src/github.com/sustainable-computing-io/kepler/vendor/github.com/prometheus/client_golang/prometheus/value.go:107
github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).Collect(0xc000400710, 0xc0000fdf60?)
        /opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/collector/collector.go:315 +0x1a76
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /opt/app-root/src/github.com/sustainable-computing-io/kepler/vendor/github.com/prometheus/client_golang/prometheus/registry.go:446 +0xfb
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /opt/app-root/src/github.com/sustainable-computing-io/kepler/vendor/github.com/prometheus/client_golang/prometheus/registry.go:538 +0xb0b

```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sunya-ch** [comment]
@jichenjc Thank you for reporting issue.
Would you mind sharing the head part from the kepler-exporter log?
This may help scope down and debug the missing labels.

```bash
2022/09/05 07:30:23 InitSliceHandler: &{map[] /sys/fs/cgroup/system.slice /sys/fs/cgroup/system.slice /sys/fs/cgroup/system.slice}
use sysfs to obtain power
2022/09/05 07:30:23 Available counter metrics: [cpu_cycles cpu_instr cache_miss]
2022/09/05 07:30:23 Available cgroup metrics: [cgroupfs_system_cpu_usage_us cgroupfs_user_cpu_usage_us cgroupfs_memory_usage_bytes cgroupfs_cpu_usage_us]
2022/09/05 07:30:23 Available kubelet metrics: [container_cpu_usage_seconds_total container_memory_working_set_bytes]
2022/09/05 07:30:23 set coreMetricIndex = 1
2022/09/05 07:30:23 set generalMetricIndex = 1
2022/09/05 07:30:23 set dramMetricIndex = 3
config EnabledEBPFCgroupID enabled:  true
```

**Comment by jichenjc** [comment]
thanks for comments, here's start of log

```
# kubectl logs kepler-exporter-6qnsf -n monitoring |head
2022/09/05 06:34:10 InitSliceHandler: &{map[] /sys/fs/cgroup/cpu /sys/fs/cgroup/memory /sys/fs/cgroup/blkio}
cpu architecture Haswell, dram in GB 31
use power estimate to obtain power
2022/09/05 06:34:10 Available counter metrics: [cpu_cycles cpu_instr cache_miss]
2022/09/05 06:34:10 Available cgroup metrics: []
2022/09/05 06:34:10 Available kubelet metrics: [container_cpu_usage_seconds_total container_memory_working_set_bytes]
2022/09/05 06:34:10 set coreMetricIndex = 1
2022/09/05 06:34:10 set generalMetricIndex = 1
2022/09/05 06:34:10 set dramMetricIndex = 3
config EnabledEBPFCgroupID enabled:  true

```

worthy note is seems the pod become Running after failure above..
not sure what pod/actions did the magic as I didn't do anything..

```
# kubectl get pods -n monitoring -o wide  | grep kepler-exporter
kepler-exporter-6qnsf                  1/1     Running   2 (79m ago)   89m   172.18.0.2    kind-control-plane   <none>           <none>
```

**Comment by jichenjc** [comment]
`curl localhost:9102/metrics` run this will cause the pod to crash as reported above ...

**Comment by sunya-ch** [comment]
Thank you for proving the log and reporting this issue.
The exported labels is 20 if no frequency option enable in BPF (`-DCPU_FREQ`).
My guess is it is a bug that when determining the prometheus label `EnableCPUFreq` is true before attacher can check the failure. 
Could you try grepping `-DCPU_FREQ` from kepler log to confirm this assumption?

**Comment by jichenjc** [comment]
thanks for the tip, yes, something wrong here,
I don't know what happened here , need dig more as brand new here :)

```
kubectl logs kepler-exporter-6qnsf -n monitoring | grep DCPU_FREQ
failed to attach perf module with options [-DNUM_CPUS=8 -DCPU_FREQ]: failed to load sched_switch: error loading BPF program: permission denied

```

**Comment by sunya-ch** [comment]
@jichenjc Thank you for confirming this. 
Hope it can be fixed by this PR: https://github.com/sustainable-computing-io/kepler/pull/135

**Comment by sunya-ch** [comment]
Also, it seems the BPF cannot be attached to your system even with only `DNUM_CPUS` option due to `permission denied` at loading. 
Could you provide the VM OS and kernel version?

**Comment by sunya-ch** [comment]
I think the current version of kepler is not compatible with BPF library on Ubuntu yet. 
One of our team is now working on that. 

If it becomes available, BPF should be able to be attached and track CPU time of the process.
Running on top of VM would affect the visibility of physical file system and some data may not be available such as  RAPL power, CPU frequency, and hardware counters.

**Comment by jichenjc** [comment]
>>>I think the current version of kepler is not compatible with BPF library on Ubuntu yet.
One of our team is now working on that.

I might miss this info, so I have to run on RHEL ? I will give a try
