### ISSUE TITLE
why use http to get pod instead of using native k8s call

### ISSUE THREAD

**Issue by jichenjc** [sustainable-computing-io/kepler#141]
**Is your feature request related to a problem? Please describe.**

looks like we are using this to get pods info ,it works but why we don't use k8s native way as it seems 
widely used in k8s world ? 
```
podUrl = "https://" + nodeName + ":" + port + "/pods"
        metricsUrl = "https://" + nodeName + ":" + port + "/metrics/resource"
```

something like

return client.CoreV1().Pods("").Watch(context.TODO(), metav1.ListOptions{} etc?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rootfs** [comment]
It is a design choice to be more scalable. The native k8s Pod API is to access the API server, while the kubelet call through HTTP(s) is initiated and ended on each node. The former will stress the API server when there are many nodes, while the latter doesn't have this issue.
