### ISSUE TITLE
"Other" metrics are out of proportion on local Kind cluster

### ISSUE THREAD

**Issue by raymundovr** [sustainable-computing-io/kepler#1416]
### What happened?

I've been running Kepler via a Kind cluster on my development laptop for the last couple of months. In recent days, I have discovered that the metrics, obtained via Prometheus, were displaying energy information (Watts) out of proportion. After taking a look I have noticed that the "other" counter are showing extremely large numbers and, due to the way that these are calculated, assigning it to the energy consumption of my deployments.

See images:
![Screenshot from 2024-05-08 14-27-27](https://github.com/sustainable-computing-io/kepler/assets/108420/08e91af1-cc07-46a5-b777-c58f75e5d5fa)

<img width="812" alt="Captura de pantalla 2024-05-09 a la(s) 12 19 53" src="https://github.com/sustainable-computing-io/kepler/assets/108420/727997f6-fe0d-41ff-82c4-aaccdc3659c7">

### What did you expect to happen?

The metrics were more close to real deployment consumption.

### How can we reproduce it (as minimally and precisely as possible)?

Unfortunately I don't have precise information on this. Cannot determine when and how it started,  my Prometheus metrics only go as far as last boot.

### Kepler image tag

<details>
From the pod labels:
helm.sh/chart: kepler-0.5.5
app.kubernetes.io/name: kepler
app.kubernetes.io/component: exporter
app.kubernetes.io/version: "release-0.7.2"
app.kubernetes.io/managed-by: Helm
</details>

### Kubernetes version

<details>
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
</details>

### Cloud provider or bare metal

<details>
Bare metal. Kind local cluster.
</details>

### OS version

<details>
```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

$ uname -a
Linux ray-levv 6.8.0-11-generic #11-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb 14 00:29:05 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SamYuan1990** [comment]
[kind](https://sigs.k8s.io/kind) is a tool for running local Kubernetes clusters using Docker container “nodes”.
kind was primarily designed for testing Kubernetes itself, but may be used for local development or CI.
so, as CI maintainer would like to suggest as just use kind for CI usage to deploy kepler on that cluster for testing.
but I am interesting with what are the specific setting/config on kind should be enabled for kepler to get power consumption data.
