### ISSUE TITLE
failed to read cpus.yaml

### ISSUE THREAD

**Issue by dave-tucker** [sustainable-computing-io/kepler#1492]
### What happened?

When running kepler as a developer I see log messages related to missing files in `/var/lib/kepler/data/cpus.yaml` when running kepler locally as part of my dev/test cycle.

### What did you expect to happen?

There not to be issues when running locally.
We should check for the presence of a `data` directory when running locally - similar to how we detect the bytecode paths in `pkg/bpf`.

### How can we reproduce it (as minimally and precisely as possible)?

```
make build
sudo ./.output/bin/linux_amd64/kepler
```

### Kepler image tag

<details>

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider or bare metal

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sthaha** [comment]
closed by https://github.com/sustainable-computing-io/kepler/pull/1572
