### ISSUE TITLE
running UT at /kepler/pkg/pod_lister always Success

### ISSUE THREAD

**Issue by jichenjc** [sustainable-computing-io/kepler#154]
**Describe the bug**

no matter condition it is , always success due to 
```
failed to get response: failed to read from "/var/run/secrets/kubernetes.io/serviceaccount/token": open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directorytesting: warning: no tests to run
PASS
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jichenjc** [comment]
root cause is following function will already run at init so it will httpGet and failed with above error

func init() {
        updateListPodCache("", false)
}

**Comment by sunya-ch** [comment]
I think there is no unit test case applied for pod lister yet.
You should add RegisterFailHandler and RunSpecs to make it as the example in suite_test.go in cgroup/collecter/model.
https://github.com/sustainable-computing-io/kepler/blob/c65de66ea9325920561f02c97cb68934d5d29fef/pkg/cgroup/suite_test.go#L27

more information about ginkgo test here: https://onsi.github.io/ginkgo/

The init function will just log that the token path is not available. It should not make the test pass or failed except you put it in the test case.

**Comment by jichenjc** [comment]
I put a very simple test in the folder 

```
(base) root@jitest19:~/kepler/pkg/pod_lister# go test ./...
ok      github.com/sustainable-computing-io/kepler/pkg/pod_lister       (cached)
(base) root@jitest19:~/kepler/pkg/pod_lister# cat pod_lister_test.go
package pod_lister

import (

        . "github.com/onsi/ginkgo"
        . "github.com/onsi/gomega"
)

var _ = Describe("Bdfasdyte order test", func() {
        It("Byte ordeafdsasdfr test", func() {
                a := "111c"
                Expect(a).To(Equal("c"))
        })
})
(base) root@jitest19:~/kepler/pkg/pod_lister#

```

and it apparently is not correct

**Comment by jichenjc** [comment]
ok, let me try this

**Comment by jichenjc** [comment]
indeed, sorry for confusion

**Comment by sunya-ch** [comment]
Good to hear that it's solved :)
