### ISSUE TITLE
BPF related metrics were zero

### ISSUE THREAD

**Issue by YaSuenag** [sustainable-computing-io/kepler#1580]
### What happened?

I tried to collect metrics with Kepler, but most of metrics relates to BPF were zero as following:

```
kepler_container_cpu_cycles_total{container_id="74da5e724660dac02b8dbcba8e2cbd12b150e7b96d38158022839df534c37f5f",container_name="prometheus",container_namespace="monitoring",pod_name="prometheus-kube-prometheus-stack-1",source="bpf"} 0
```

Kepler log reports 0 CPU cycle were consumed - it is unbelievable!

```
I0701 08:35:29.474728       1 process_bpf_collector.go:88] process prometheus (pid=262348, cgroup=47273) has 0 task clock time 0 CPU cycles, 0 instructions, 0 cache misses, 0 page cache hits
```

### What did you expect to happen?

Can be collected all of metrics via eBPF.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy Kepler on Kubernetes v1.30 with Cilium on Rocky Linux 9.4

### Kepler image tag

<details>
release-0.7.10
</details>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1
```

</details>

### Cloud provider or bare metal

<details>
bare metal
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"

$ uname -a
Linux linux-test 5.14.0-427.13.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Wed May 1 19:11:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

I installed Kepler via Helm, and it works as daemonset. So following commands did not work.

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE}
<None>

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE}
<None>
```

</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRI-O v1.30.2
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Cilium v1.15.6
</details>

**Comment by rootfs** [comment]
this should be fixed in #1542
