### ISSUE TITLE
Kepler not running in Raspberry Pis

### ISSUE THREAD

**Issue by ravaga** [sustainable-computing-io/kepler#1597]
### What happened?

I tried to install Kepler in a K3s cluster composed of:

- Raspberry Pi 4, 4GB RAM, Ubuntu 22.04
- Raspberry Pi 3, 1GB RAM, Raspberry Pi OS 12

with the Helm chart:
`helm install kepler kepler/kepler --namespace kepler --create-namespace --set serviceMonitor.enabled=true --set serviceMonitor.labels.release=prometheus`

However, the Kepler containers fail with these logs:

```bash
libbpf: failed to find valid kernel BTF
libbpf: Error loading vmlinux BTF: -3
libbpf: failed to load object '/var/lib/kepler/bpfassets/kepler.bpfel.o'
F0705 12:00:29.218890       1 exporter.go:109] failed to create eBPF exporter: failed to load eBPF object: failed to load BPF object: no such process
```

After it, I have checked that it seems that BTF is not present in the Kernel of both machines and _/sys/kernel/btf/vmlinux_ is not present.

### What did you expect to happen?

Install Kepler in all the nodes of the K3s cluster.

### How can we reproduce it (as minimally and precisely as possible)?

Create a K3s cluster with at least a Raspberry Pi and then install Kepler using the Helm chart:

``helm install kepler kepler/kepler --namespace kepler --create-namespace --set serviceMonitor.enabled=true --set serviceMonitor.labels.release=prometheus``

### Kepler image tag

<details>
Used container image (for ARM64 arch):
quay.io/sustainable_computing_io/kepler:release-0.7.10
</details>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.3+k3s2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3+k3s2
```

</details>

### Cloud provider or bare metal

<details>
Bare metal in Raspberry Pis (ARM64 arch)
</details>

### OS version

<details>

```console
# Raspberry Pi 4:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux raspberrypi4 5.15.0-1055-raspi #58-Ubuntu SMP PREEMPT Sat May 4 03:52:40 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```
```console
# Raspberry Pi 3:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux raspberrypi 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE}
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE}
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.7.11-k3s2 and containerd://1.7.7-k3s1
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Cilium v1.14.2 as CNI
</details>

**Comment by dave-tucker** [comment]
Looks like the RPi Kernels aren't being compiled with `CONFIG_DEBUG_INFO_BTF=y`.
Unfortunately the only fix is to [re-compile your kernel ](https://www.raspberrypi.com/documentation/computers/linux_kernel.html#configure-the-kernel) with BTF support or to use a RPi image that already has this enabled.
