### ISSUE TITLE
add badges in readme

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/kepler#160]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**

- [ ] go doc
- [ ] go test coverage
- [ ] CI

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by xiaopeng-zh** [comment]
@SamYuan1990 Can I take this one?

**Comment by SamYuan1990** [comment]
> @SamYuan1990 Can I take this one?

welcome

**Comment by xiaopeng-zh** [comment]
There are two ways to set the `go test coverage` badge.

- Static way: Just hardcode the percentage of coverage but needs to update the data when the value changes.
- Dynamic way: Get the latest coverage data & update it automatically. Ref: [go-coverage-badge](https://github.com/marketplace/actions/go-coverage-badge)

@SamYuan1990 Which way is suitable for us now?

**Comment by SamYuan1990** [comment]
> There are two ways to set the `go test coverage` badge.
> 
> * Static way: Just hardcode the percentage of coverage but needs to update the data when the value changes.
> * Dynamic way: Get the latest coverage data & update it automatically. Ref: [go-coverage-badge](https://github.com/marketplace/actions/go-coverage-badge)
> 
> @SamYuan1990 Which way is suitable for us now?

I suppose if the dynamic way means the test coverage will updated once after each PR merged, then I prefer dynamic way.  
we should not update data for test coverage in manual. 

@rootfs , any comments?

**Comment by rootfs** [comment]
dynamic way it is, thank you @xiaopeng-zh for taking this!

**Comment by xiaopeng-zh** [comment]
Ref: https://github.com/sustainable-computing-io/kepler/pull/189, the PR merged, this can be closed.
