### ISSUE TITLE
Add lint and memory leak detection as a basic test case in CI 

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/kepler#161]
**Is your feature request related to a problem? Please describe.**
Before unit test running, we'd better have a lint test and memory leak detection as a part of CI.

**Describe the solution you'd like**
`go fmt, vet, goimports ....`
```
go build -gcflags="-m -l" ./... | grep "escapes to heap" || true
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rootfs** [comment]
in addition to memory leak, please also consider [vulnerability detection](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck)
