### ISSUE TITLE
Enhance CI with basic integration test

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/kepler#162]
**Is your feature request related to a problem? Please describe.**
So far, we just verify by `until kubectl get svc --all-namespaces  ...`
to make it better, we'd better have a test suite and targeting on running service.

**Describe the solution you'd like**
as above.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rootfs** [comment]
The service readiness detection is to be supported in kepler-operator

**Comment by sallyom** [comment]
this issue is folded into https://github.com/sustainable-computing-io/kepler/issues/350, closing here and moving conversation to  #350 tracked on the Project Board
