### ISSUE TITLE
add the custom `metal-runner-action@custom-action` in sustainable-computing org

### ISSUE THREAD

**Issue by vimalk78** [sustainable-computing-io/kepler#1739]
checkin the custom `metal-runner-action@custom-action` into sustainable-computing org

_Originally posted by @vimalk78 in https://github.com/sustainable-computing-io/kepler/pull/1738#discussion_r1732235011_

**Comment by vprashar2929** [comment]
The same can be done for https://github.com/rootfs/metal-delete-action as we also use a custom version of this

**Comment by vprashar2929** [comment]
closing as #1769 got merged
