### ISSUE TITLE
Kepler process / vm bpf cpu time jitters quite a lot compared to node-exporter cpu time

### ISSUE THREAD

**Issue by sthaha** [sustainable-computing-io/kepler#1806]
Kepler Version: 
* 
kepler_exporter_build_info{arch="amd64", branch="main", instance="vm:9100", job="vm", os="linux", revision="8672dc3cf70a20bdadb5f8680699e812ef0998f5", version="v0.7.11-254-g8672dc3c-dirty"} | 1
* kepler_exporter_build_info{arch="amd64", branch="main", instance="kepler-metal:8888", job="metal", os="linux", revision="8672dc3cf70a20bdadb5f8680699e812ef0998f5", version="v0.7.11-254-g8672dc3c-dirty"}

Steps to reproduce 
* Run any dev or validation/metal or validation/vm [compose for kepler ](https://github.com/sustainable-computing-io/kepler/tree/main/manifests/compose)
* Run stress-ng that stresses the machine for some time
* Open Prometheus and run `sum(rate(kepler_process_bpf_cpu_time_ms_total{job="metal"}[20s]))`

See the jitter as below 
![image](https://github.com/user-attachments/assets/bb7fefd0-a8d3-44e7-99c8-872f7d63dcd8)
![image](https://github.com/user-attachments/assets/fb89d8a2-0a2a-44c8-9abf-fa488e03dcf4)

### Node Exporter CPU time vs Kepler 
* node-exporter in green is almost a straight line 
* sum(rate(kepler_vm_package_joules_total{job="metal"}[20s]))  in red 
* sum(rate(kepler_process_bpf_cpu_time_ms_total{job="vm" pid!="1"}[20s])) in yellow

![image](https://github.com/user-attachments/assets/c3612053-96ff-416a-bc65-2702f1f1df09)

Zoomed: 

![image](https://github.com/user-attachments/assets/1980c755-7db7-44a6-9698-17e1e5565f56)

**Comment by vimalk78** [comment]
can this be closed?

**Comment by sthaha** [comment]
Yes, this jitter happens if the scrape interval is less than kepler's update interval of 3s
