### ISSUE TITLE
Disable Idle/Dynamic Separation in Kepler

### ISSUE THREAD

**Issue by KaiyiLiu1234** [sustainable-computing-io/kepler#1811]
Add flag to allows users to disable Idle/Dynamic Separation in Kepler, so Kepler only exports direct power measurements. Idle/Dynamic Separation is faulty and also complicates the validation process.

**Comment by aharivel** [comment]
This is an interesting statement. Could you elaborate why this is faulty ? Overall I agree with the fact that it is easier to only have one value.

**Comment by KaiyiLiu1234** [comment]
From a previous test, idle power never goes down. It seems to always select the maximum "total power" and sticks to it. So what happens is if you stress the cpu to 100%, idle will adopt this power and sticks to it. When the stressing stops, the total power from rapl goes down but idle assigned by kepler does not change. When dynamic is calculated with max(total power - idle power, 0), dynamic is stuck at 0 after the first stress and idle is stuck at the highest power level.

**Comment by KaiyiLiu1234** [comment]
Flag has been added so the issue can be closed.

**Comment by aharivel** [comment]
Could you give the link to the PR that add the flag please ? Thanks
