### ISSUE TITLE
Kepler e2e MAPE is not in percentage form

### ISSUE THREAD

**Issue by KaiyiLiu1234** [sustainable-computing-io/kepler#1822]
Ref: https://github.com/sustainable-computing-io/kepler/blob/main/e2e/tools/validator/src/validator/prometheus/__init__.py#L119

scikit mape provides a decimal. The percentage is derived by multiplying mean_absolute_percentage_error with 100.

cc: @rootfs

**Comment by vprashar2929** [comment]
closing as #1824 addresses this
