### ISSUE TITLE
add DCO check?

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/kepler#186]
**Is your feature request related to a problem? Please describe.**
I am not sure if we should enable https://github.com/dcoapp/app to ensure everyone signed their commit in pr.

**Describe the solution you'd like**
n/A

**Describe alternatives you've considered**
n/A

**Additional context**
n/A

**Comment by cooktheryan** [comment]
+1

**Comment by marceloamaral** [comment]
+1
