### ISSUE TITLE
Inconsistent Kepler container generation between Upstream / Downstream

### ISSUE THREAD

**Issue by aharivel** [sustainable-computing-io/kepler#1891]
### What happened?

During our development, we faced the issue that the command line `ss` is  present in Upstream but not Downstream. 
Sadly we developed our Health Check using this command line and it's not working Downstream.

### What did you expect to happen?

We expect the Upstream and the Downstream container to be exactly the same for a given version. 

### How can we reproduce it (as minimally and precisely as possible)?

Downstream version doesn't have `ss` :
registry.redhat.io/openshift-power-monitoring/kepler-rhel9:v0.7.12-9

Upstream version has `ss` : 
quay.io/sustainable_computing_io/kepler:release-0.7.12 

### Kepler image tag

<details>
v0.7.12-9
</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider or bare metal

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE}
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE}
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by vimalk78** [comment]
the difference is because the base images are different.  upstream 0.7.12 uses ubi9 as the base image and downstream uses ubi9-minimal. which explains absence of `ss` utility in downstream.
Going forward, upstream kepler is also using ubi9-minimal as base image and so will no longer contain the ss utility.
