### ISSUE TITLE
Add Kepler to eBPF landscape

### ISSUE THREAD

**Issue by xmulligan** [sustainable-computing-io/kepler#190]
**Is your feature request related to a problem? Please describe.**
Add Kepler to the eBPF Landscape https://ebpf.io/applications

**Describe the solution you'd like**
It would be great if you could open a PR like https://github.com/ebpf-io/ebpf.io-website/pull/246

**Describe alternatives you've considered**
N/A

**Additional context**
We love to see the eBPF community grow 🐝

**Comment by rootfs** [comment]
this is a good idea @xmulligan

**Comment by xmulligan** [comment]
Thanks! Looking forward to getting it added before eBPF Summit next week

**Comment by rootfs** [comment]
@xmulligan PR opened at https://github.com/ebpf-io/ebpf.io-website/pull/255, review appreciated, thanks
