### ISSUE TITLE
cover: open coverage.out: no such file or directory

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#193]
**Describe the bug**
go coverage CI error

```
--- PASS: TestPodLoader (0.00s)
PASS
coverage: 24.6% of statements
ok  	github.com/sustainable-computing-io/kepler/pkg/podlister	0.052s
?   	github.com/sustainable-computing-io/kepler/pkg/power/acpi	[no test files]
?   	github.com/sustainable-computing-io/kepler/pkg/power/gpu	[no test files]
?   	github.com/sustainable-computing-io/kepler/pkg/power/rapl	[no test files]
?   	github.com/sustainable-computing-io/kepler/pkg/power/rapl/source	[no test files]
cover: open coverage.out: no such file or directory
Error: Process completed with exit code 1.
```

**To Reproduce**
This is in this [run result](https://github.com/sustainable-computing-io/kepler/actions/runs/3071410020/jobs/4962047268)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootfs** [comment]
cc @xiaopeng-zh

**Comment by SamYuan1990** [comment]
@rootfs , I will update ...
btw, I hope you can merge the PR in carefully .... https://github.com/sustainable-computing-io/kepler/actions/runs/3066091930/jobs/4961441566#step:6:358
