### ISSUE TITLE
log/println usage

### ISSUE THREAD

**Issue by jichenjc** [sustainable-computing-io/kepler#212]
**Is your feature request related to a problem? Please describe.**

we use fmt.Println , log.Println etc in code

we should follow best practice to include log only 
and use different level such as Log.V(3) / V(4) etc to show different logs with different level

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by marceloamaral** [comment]
Right, this was in my TODO list...

It will be great to have different verbosity levels....

**Comment by rootfs** [comment]
closed by #238
