### ISSUE TITLE
CI: don't run test post PR merge

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#222]
**Is your feature request related to a problem? Please describe.**
CI: don't run test post PR merge

**Describe the solution you'd like**
Currently the CI runs tests and commit post PR merge, this takes time to see the merge. Since the tests are already executed when the PR is opened,  we only need to commit changes once the PR is merged

**Describe alternatives you've considered**

**Additional context**
@SamYuan1990

**Comment by marceloamaral** [comment]
If it is tested pre merge, do we need to test again post merge?

**Comment by SamYuan1990** [comment]
> If it is tested pre merge, do we need to test again post merge?

for unit test, we relay on it for test coverage badge.
for docker build, yes, there no unit test for image. in fact test for docker file equals with build isn't it?
for integration test ... as I said, the reason is to ensure user use this project and receive a good result.

any comments?

**Comment by SamYuan1990** [comment]
@rootfs , are we good enough with necessary post action running for now?

**Comment by SamYuan1990** [comment]
I suppose so far it take about 5 mins for PR as the integration test take the longest time.
for post merge, I am not sure if we can save 1 more minutes as `CTR_CMD = docker`?
I am going to take a rest. as to tired to making mistake as https://github.com/sustainable-computing-io/kepler/pull/229 ...
will check msg tomorrow to avoid making more mistake.

**Comment by rootfs** [comment]
kind test takes a bit longer but overall quite an improvement
![image](https://user-images.githubusercontent.com/7062400/191563704-6d02e0e4-4238-4c09-a5ed-3b07f5c23f1f.png)
