### ISSUE TITLE
Attributing block I/O energy

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#252]
**Is your feature request related to a problem? Please describe.**
Currently the attribution to Pods is based the Pods CPU/memory activities. The processes in the Pods could have disk I/O activities that are handled by interrupt handlers, we should attribute energy consumed by the handlers properly to the Pods that initiate them.

**Describe the solution you'd like**
The I/O stats are collected by cgroupfs. The interrupt handlers are currently classified as system processes. 
In the first implementation, we can do the following flow
- get the kworker process(es) that handle(s) the disk I/Os, quantify the processes' energy consumption.
- from the process's cgroup disk I/O stat, find the block I/O stats on each block device
- evenly distribute the kworker's energy to all processes based on their I/O stats
- create another metrics for the pods called Pod disk I/O energy

We can quantify other I/O energy in similar way, e.g. network I/O.

**Comment by rootfs** [comment]
Per kernel source [here](https://github.com/torvalds/linux/blob/3d7cb6b0/block/blk-core.c#L1260), the block I/O worker threads name regex is `^[kworker/.*kblockd]$`, e.g. `[kworker/93:1H-kblockd]`

**Comment by marceloamaral** [comment]
Thanks @rootfs for writing the summary of the idea here!

**Comment by rootfs** [comment]
https://github.com/orgs/sustainable-computing-io/teams/kepler-core
