### ISSUE TITLE
CI post action enhance

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/kepler#254]
**Is your feature request related to a problem? Please describe.**
- remove post integration test
- image build from base to kepler

**Describe the solution you'd like**
n/A

**Describe alternatives you've considered**
n/A

**Additional context**
n/A

**Comment by SamYuan1990** [comment]
@marceloamaral , could you please add some reason in comments for remove post integration test checking?

**Comment by marceloamaral** [comment]
I'm not saying that post-integration testing isn't useful, there may be some use cases that will be needed

However, for simplicity's sake for now, I think that our integration test should be run before the merge

**Comment by SamYuan1990** [comment]
> I'm not saying that post-integration testing isn't useful, there may be some use cases that will be needed
> 
> However, for simplicity's sake for now, I think that our integration test should be run before the merge

I am going to create a pr for this and let's see.

**Comment by SamYuan1990** [comment]
close for now as resolved by #267
