### ISSUE TITLE
Selectively export metrics

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#258]
**Is your feature request related to a problem? Please describe.**
Currently all metrics are exported. This will create a long list of metrics when there are many pods.

**Describe the solution you'd like**
The exported metrics can be set during startup as well as runtime, potentially through a configmap

**Comment by marceloamaral** [comment]
We have groups of metrics, so that we could enable and disable it via command line parameter

**Comment by jichenjc** [comment]
>>> This will create a long list of metrics when there are many pods.

we will switch from pod to container mode soon, I believe this issue will not be impacted by that plan/PR ? 
@marceloamaral

**Comment by marceloamaral** [comment]
I don't think we're going to disable power consumption metrics, but there are some extra metrics.

For example, we export hardware counters (HC) of containers. Although we have the logic to disable it if HC is not available, we could also make it optional and disable HC even when it is available.

Also, I think there is a plan to expose some cgroup metrics that we're using, and it will be nice to be able to enable and disable them as well.

**Comment by jichenjc** [comment]
ok, thanks, I think at least the counters is eligible for that, thanks for sharing this

**Comment by jichenjc** [comment]
>>>I think there is a plan to expose some cgroup metrics that we're using, and it will be nice to be able to enable and disable them as well.

I think we are not there yet, do we?

**Comment by marceloamaral** [comment]
Not now....
