### ISSUE TITLE
Separating system processes from Pod energy metrics

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#261]
**Is your feature request related to a problem? Please describe.**
Currently for consistency, all the system processes are classified as system processes Pod and in system namespace. 
This is a problem for end user and becomes unscalable when further separating kblockd and softirq from the system processes.

**Describe the solution you'd like**
The system processes, kblockd, ksoftirqd and any upcoming non-Pod identities should have their own metrics, not to be mixed in the Pods metrics.

**Comment by rootfs** [comment]
> We can have this information in the same metric, as it will be easier to aggregate and manipulate the information in Prometheus But instead of using the pod name label, we should leave that label empty and have another label called process_name Wdyt?

sounds good!

**Comment by jichenjc** [comment]
I saw there are multiple PR/issues to separate the kblockd etc, so any todo for this issue (only) ?

**Comment by marceloamaral** [comment]
This is a WIP and needs more design thinking
