### ISSUE TITLE
podName without ns?

### ISSUE THREAD

**Issue by jichenjc** [sustainable-computing-io/kepler#265]
**Describe the bug**

we can have same name pod 
```
# kubectl get pods -A | grep counter
default       counter                                    1/1     Running   1 (47h ago)   2d13h
n1            counter                                    1/1     Running   0             8s

```
but https://github.com/sustainable-computing-io/kepler/blob/main/pkg/collector/reader.go#L133
seems we only honor the podname , is this on purpose design? 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootfs** [comment]
nice catch! This needs another checking. In an [early implementation](https://github.com/sustainable-computing-io/kepler/blob/3887805f2a85848d4b75ece67e60ace1feab759c/pkg/collector/reader.go#L116-L120), the map is indexed by `podName-namespace`.

**Comment by rootfs** [comment]
@jichenjc you like to stand up a fix and test case?

**Comment by jichenjc** [comment]
yes, I can give a try

**Comment by marceloamaral** [comment]
Nice catch, we need to use maybe the pod ID instead in the pod name in the structure 
Regarding the prometheus metric, it has the pod name and namespace labels

**Comment by jichenjc** [comment]
I tried to add a PR and I think the best fit would be pod ID ,but looks like we are using [1] for containerID but I think it can't be used as we are looking for podID, do we have any reference that I can steadily get a pod ID? @rootfs @marceloamaral 
or I can actually use `namespace/podname` so it will anyway help as well (and maybe better due to smaller footprint than a long pod ID ..?



[1] https://github.com/sustainable-computing-io/kepler/blob/main/pkg/podlister/resolve_container.go#L168

**Comment by rootfs** [comment]
@jichenjc `podName` is the map key, once the cGroupID/PID is resolve and `ppodName` is known, we don't need `containerID`.  If you use `namespace/podname`, that looks a good PodID. There is a length limit of namespace and pod name. In the very unfortunate case of long names, a SHA will be a good to go.

**Comment by marceloamaral** [comment]
We could add the podID in the container info structure:
https://github.com/sustainable-computing-io/kepler/blob/main/pkg/podlister/resolve_container.go#L141
And them, we can have a function to get the podID

**Comment by jichenjc** [comment]
@marceloamaral you mean use the `i` https://github.com/sustainable-computing-io/kepler/blob/main/pkg/podlister/resolve_container.go#L137 to be pod id ? 

I actually checked 
https://github.com/sustainable-computing-io/kepler/blob/6d334c689d13cdefdee2b443e07c4a39ba8b42b8/vendor/k8s.io/api/core/v1/types.go#L3962

both PodSpec and PodStatus seems doesn't have `id` field can be used .. 

so I will follow `namespace/podname` case based on @rootfs 's suggestion and update it (after our holiday).. thanks

**Comment by marceloamaral** [comment]
@jichenjc Actually you can have the pod ID from the metadata as follow:
```
podID := (*pods)[i].ObjectMeta.UID
```

I think it is better to use a definitive solution that will not have any problem in the future....

**Comment by jichenjc** [comment]
ok,then this comes to uuid of the pod :) , will do a quick test, thank ~
