### ISSUE TITLE
enhance reader.go logic with *enableGPU parameter

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/kepler#276]
so far if there no gpu device, the code still go through with gpu logic for example: `podGPUDelta`
as we have `*enableGPU`, if `GPU` is disabled, can we skip gpu related logic?

_Originally posted by @SamYuan1990 in https://github.com/sustainable-computing-io/kepler/discussions/273#discussioncomment-3787199_

**Comment by marceloamaral** [comment]
I think the logic should try to discover gpus.
So, if there is no gpus in the system we disable the calculation.

Will you submit a PR for this?

**Comment by SamYuan1990** [comment]
> I think the logic should try to discover gpus. So, if there is no gpus in the system we disable the calculation.
> 
> Will you submit a PR for this?

not for now @marceloamaral , I am no local holiday...
if you want it, you can pick it up for now.

**Comment by rootfs** [comment]
@SamYuan1990 enjoy the holiday!

**Comment by marceloamaral** [comment]
The PR #287 fix this
