### ISSUE TITLE
Add option to set CPU type

### ISSUE THREAD

**Issue by nikimanoledaki** [sustainable-computing-io/kepler#277]
**Is your feature request related to a problem? Please describe.**
While running Kepler on a VM, the CPU type is not found.
```
# archspec cpu
x86_64_v4
```

**Describe the solution you'd like**
As a VM user, given that I know my host CPU, I would like the ability to set the CPU type manually.

**Describe alternatives you've considered**
A potential fallback/alternative, proposed by @rootfs, would be to hardcode 'unknown CPU' as a fallback CPU type in `/var/lib/kepler/data/normalized_cpu_arch.csv`.

**Comment by rootfs** [comment]
Thank you for the suggestion. We can add an env var to allow end user to set the default cpu type. Note, this works on a homogeneous environment.
