### ISSUE TITLE
Add flag to enable VM deployment during CI

### ISSUE THREAD

**Issue by jichenjc** [sustainable-computing-io/kepler#299]
**Is your feature request related to a problem? Please describe.**

https://github.com/sustainable-computing-io/kepler/pull/294#issuecomment-1278354596

I am very curious why the current deployment can pass in CI ,though @marceloamaral @rootfs 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by marceloamaral** [comment]
The PR #294 does not deploy Kepler to nodes that have the label:
`feature.node.kubernetes.io/cpu-cpuid.HYPERVISOR`

So, as I mentioned, this is very specific to someone's infrastructure....
This means that other infrastructures, even if they are running on top of VMs, may not have this label...

**Comment by rootfs** [comment]
cc @ruomengh

**Comment by jichenjc** [comment]
Added a couple of comments in #294 
in summary, I think we should agree there before we do any actions here

**Comment by ruomengh** [comment]
Actually this depends on NFD (node feature discovery) and this NFD works for x86 architecture only. Please refer to https://kubernetes-sigs.github.io/node-feature-discovery/v0.11/get-started/features.html#arm-cpuid-flags-partial-list
This could affect environments which don't have NFD deployed or which are not x86.

**Comment by jichenjc** [comment]
yes, I found that and commented in #294 with exactly same thing you described

I am not sure whether we need introduce such dependency and deployment for such minor feature 
happy to get folks to comment...

**Comment by marceloamaral** [comment]
I am closing this issue since we agreed to not add such a flag.
But we can open it again if needed.
