### ISSUE TITLE
Cannot deploy Kepler with make cluster-sync

### ISSUE THREAD

**Issue by marceloamaral** [sustainable-computing-io/kepler#318]
**Describe the bug**
After merging PR #311 the kepler deployment is not working anymore

```
kustomize manifests...
+ kubectl kustomize _output/manifests/kubernetes/generated/bm
Error: rawResources failed to read Resources: Load from path ../base failed: '../base' must be a file (got d='/home/mamaral/go/src/github.com/marceloamaral/kepler/_output/manifests/kubernetes/generated/base')
```

**To Reproduce**
` make cluster-sync`

**Comment by jichenjc** [comment]
yes, I found this , working on this now ,sorry for inconvenience

**Comment by marceloamaral** [comment]
Thanks @jichenjc for the quick reply...

Don't worry, but I am wondering why the tests did not get this....

**Comment by jichenjc** [comment]
let me fix the issue first then find why test not find it

**Comment by marceloamaral** [comment]
@jichenjc the problem is the `kubectl` version: [here](https://stackoverflow.com/questions/67071962/kubectl-apply-k-throws-error-rawresources-failed-to-read-resources-load-from ). That's why we didn't see this in the CI...

After updating my `kubectl`, the deployment process is working now...

Unfortunately I don't know which version I had before... but we should document this dependency somewhere

**Comment by jichenjc** [comment]
Thanks for sharing this, I found something still need improve, will submit a PR soon

**Comment by marceloamaral** [comment]
But the `make cluster-sync` is still not working....

For the CI, I upload the new built image to the kind cluster...
In order to use this image, we need to change the manifest to use the new image....[here](https://github.com/sustainable-computing-io/kepler/blob/main/hack/build-manifest.sh#L43)

But the image name is not being updated now...

**Comment by jichenjc** [comment]
yes, I found that bug, working on that now .. will submit a PR soon

**Comment by jichenjc** [comment]
looks like the deployment of make cluster-sync is different to manifest.. need update them as well

**Comment by marceloamaral** [comment]
Here is how to fix it:
```bash
if [[ $CLUSTER_PROVIDER == "openshift" ]]; then
    cat manifests/${CLUSTER_PROVIDER}/kepler/01-kepler-install.yaml | sed "s|image:.*|image: $IMAGE_REPO:$IMAGE_TAG|" > ${MANIFESTS_OUT_DIR}/kepler/01-kepler-install.yaml
else
    cat ${MANIFESTS_OUT_DIR}/bm/deployment.yaml | sed "s|image:.*|image: $IMAGE_REPO:$IMAGE_TAG|" > tmp_file
    mv tmp_file ${MANIFESTS_OUT_DIR}/bm/deployment.yaml
    cat ${MANIFESTS_OUT_DIR}/vm/deployment.yaml | sed "s|image:.*|image: $IMAGE_REPO:$IMAGE_TAG|" > tmp_file 
    mv tmp_file ${MANIFESTS_OUT_DIR}/vm/deployment.yaml
fi
```

I updated for Kubernetes, but you need to also update it for openshift

**Comment by marceloamaral** [comment]
You just need to update the `hack/build-manifest.sh`

**Comment by jichenjc** [comment]
https://github.com/sustainable-computing-io/kepler/pull/319/ is proposed for this , thanks for report and hope that works

**Comment by marceloamaral** [comment]
Thanks!
