### ISSUE TITLE
aggregate energy consumption from Container level to higher level

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#329]
- [x] #301 
- [ ] dashboard change

0.5 release

**Comment by rootfs** [comment]
@marceloamaral join metrics at the Prometheus level. Investigate the relationship in the metadata. 
@sunya-ch not to query API server from every nodes. A controller (along with Kepler in the deployment) to expose high level API and Pods relationship to Prometheus.  Aggregation is done at Prometheus. 
@wangchen615 metrics needs to be indexed for Prometheus query. Namespace, deployment, pods....

**Comment by rootfs** [comment]
1) what metadata are already in Prometheus (e.g. Job)

**Comment by marceloamaral** [comment]
`kube-state-metric` exports the owner of objects.
So the pod created by a Job or Deployment will have this information exported.

@sunya-ch did quick test to aggregate the metrics a it works:
![image](https://github.com/sustainable-computing-io/kepler/assets/5133121/58c94556-d4ac-434f-9f4b-e23ea195e33d)

**Comment by marceloamaral** [comment]
I have created a side project to help with that, which export labels to be used to aggregate the metrics of different project, executions, etc.
https://github.com/marceloamaral/label-exporter

The plan is to migrate the label-exporter inside the sustainable-computing-io and also expose object ownership metrics as kube-state-metric.

**Comment by rootfs** [comment]
this can be resolved with label exporter provided by @marceloamaral
