### ISSUE TITLE
support more kubernetes/openshift cluster types

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#331]
- [ ] #313
- [ ] #182

**Comment by SamYuan1990** [comment]
microshift？

**Comment by sallyom** [comment]
PR for CI with OpenShift: https://github.com/openshift/release/pull/32639

**Comment by sallyom** [comment]
@rootfs please assign me to this card @sallyom thank you

**Comment by sallyom** [comment]
> how to track microshift and make it available on the CI

I believe we can utilize the openshift/release MicroShift CI, then add Kepler deployment to that - (and also add documentation to Kepler repo wrt how a user can deploy MicroShift on their own)

**Comment by sallyom** [comment]
I've been putting together the recipe for running kepler/prom/grafana in MicroShift, with KVM, will open a PR to document this

**Comment by marceloamaral** [comment]
Does the MicroShift need to be run in KVM? It would be better to run it directly in Bare-Metal.

In the case you will run in KVM, it could also be possible to enable RAPL and Hardware Counter metrics.
This is related to the issue #367.
