### ISSUE TITLE
Document deployment settings and cli options

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#333]
- [x] deployment scenarios with model server, estimator, and kepler
- [x] deployment scenarios and cli options recommended for VM and baremetal
- [x] troubleshooting guide

**Comment by marceloamaral** [comment]
+1

**Comment by jichenjc** [comment]
is this something should be tracked in sustainable computing overall doc issue? 
e.g we need update here https://sustainable-computing.io/html/installation/index.html ?

**Comment by rootfs** [comment]
@jichenjc yes, eventually all the doc will go to the https://github.com/sustainable-computing-io/kepler-doc repo

**Comment by husky-parul** [comment]
@jichenjc 
This is our documentation repo https://github.com/sustainable-computing-io/kepler-doc
When you are done with it, please create a PR on the main branch and add me as the reviewer. We use sphinx to build the html so the content goes inside [docs/source](https://github.com/sustainable-computing-io/kepler-doc/tree/main/docs/source/)

**Comment by rootfs** [comment]
bump up this issue

**Comment by rootfs** [comment]
- [x] deployment scenarios with model server, estimator, and kepler: This is supported in the Operator instruction [here](https://github.com/sustainable-computing-io/kepler-doc/blob/main/docs/usage/general_config.md)
- [ ] deployment scenarios and cli options recommended for VM and baremetal: This is also documented in the Kepler installation [here](https://github.com/sustainable-computing-io/kepler-doc/blob/main/docs/installation/kepler.md)
- [ ] troubleshooting guide.

**Comment by jichenjc** [comment]
I haven't try https://github.com/sustainable-computing-io/kepler/issues/448 personally 
but I think it might impact 
`deployment scenarios and cli options recommended for VM and baremetal: This is also documented in the Kepler installation` ？

**Comment by sunya-ch** [comment]
Is there anyone already assigned to update the doc? Otherwise, I will create a PR for that.

**Comment by rootfs** [comment]
trouble shooting guide PR is here https://github.com/sustainable-computing-io/kepler-doc/pull/34
