### ISSUE TITLE
Document metrics and their usage

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#334]
- [ ] review and improve Prometheus metrics description
- [ ] document metrics and how to use them in dashboard and query

**Comment by jichenjc** [comment]
I knew @marceloamaral is working on (already done?) container level metrics
should we first record old(legacy) metrics then continue improve?

**Comment by marceloamaral** [comment]
This is a good idea, I will work on it! I think we should already document the new container-level metrics....
Btw, we have some good discussion of how to use the metrics in #291

**Comment by husky-parul** [comment]
Hi @jichenjc and @marceloamaral 
This is our documentation repo https://github.com/sustainable-computing-io/kepler-doc
When you are done with it, please create a PR on the main branch and add me as the reviewer. We use sphinx to build the html so the content goes inside [docs/source](https://github.com/sustainable-computing-io/kepler-doc/tree/main/docs/source/)

We are going to use this issue to track the PRs so please link this issue in your PR.
Thanks.

**Comment by marceloamaral** [comment]
@husky-parul I created a PR with the detailed description of the metrics.
https://github.com/sustainable-computing-io/kepler-doc/pull/25

**Comment by jichenjc** [comment]
I think we covered this already
