### ISSUE TITLE
upgrade ginkgo to ginkgo v2

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/kepler#341]
upgrade test case to ginkgo v2

**Comment by marceloamaral** [comment]
What are the advantages and disadvantages?

**Comment by SamYuan1990** [comment]
> What are the advantages and disadvantages?

one of the advantage is that we can use ginkgo related plug-in in vscode to see test coverage in a visual way.
disadvantages: no?

**Comment by rootfs** [comment]
https://marketplace.visualstudio.com/items?itemName=joselitofilho.ginkgotestexplorer

**Comment by SamYuan1990** [comment]
@sallyom , I want to update this ticket's priority from medium to high.

**Comment by sallyom** [comment]
@SamYuan1990 :tada: thanks for this!
