### ISSUE TITLE
end-to-end integration with model server, estimator, and kepler

### ISSUE THREAD

**Issue by wangchen615** [sustainable-computing-io/kepler#349]
- [x] e2e integration
- [x] test cases for validation

**Comment by rootfs** [comment]
Currently developing the e2e integration and validation through https://github.com/sustainable-computing-io/kepler-e2e-test

**Comment by rootfs** [comment]
bump up this issue

**Comment by SamYuan1990** [comment]
are we good enough for now?
we have test case as golang code, check both metrics and value of each metric.

**Comment by rootfs** [comment]
#449 is a step to that. It gets estimator into the e2e test

**Comment by rootfs** [comment]
Kepler, estimator and model server are integrated via #449. Kepler e2e test is now available.

Next step is to brainstorm on the test cases that cover all the components and are runnable on CI.

**Comment by rootfs** [comment]
Track next step in #456
