### ISSUE TITLE
Improve integration test suite to test basic metric query

### ISSUE THREAD

**Issue by sallyom** [sustainable-computing-io/kepler#350]
[From #162](https://github.com/sustainable-computing-io/kepler/issues/162) @SamYuan1990 

**Is your feature request related to a problem? Please describe.**
So far, we just verify by `until kubectl get svc --all-namespaces  ...`
to make it better, we'd better have a test suite and targeting on running service.

**Describe the solution you'd like**
as above.

**Comment by rootfs** [comment]
@sallyom sounds good, please list the previously opened issues for this task.

**Comment by sallyom** [comment]
previous work:
- https://github.com/sustainable-computing-io/kepler/pull/283
- https://github.com/sustainable-computing-io/kepler/pull/292

**Comment by sallyom** [comment]
From #162 @rootfs & @SamYuan1990 

> The service readiness detection is to be supported in kepler-operator

> > so what's our scope of integration test?

Will open a design doc to discuss integration test goals

**Comment by SamYuan1990** [comment]
is there any thing we left in this issue?

**Comment by sallyom** [comment]
@SamYuan1990 @rootfs this merged last week, https://github.com/sustainable-computing-io/kepler/pull/357  so I believe this issue is completed! :partying_face: :tada:

**Comment by sallyom** [comment]
https://github.com/sustainable-computing-io/kepler/issues/349 will add more in-depth integration tests. The current suite satisfies this issue.
