### ISSUE TITLE
scalability and performance tests to evaluate kepler's resource usage and scrape latency under high and low workload

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#366]
marceloamaral: I can help since I was already starting by including some latency information in the code.
Btw, performance and scalability analysis was my main role in the Kubevirt project.

We will need to define what is high and low workload.
I currently have a single node cluster, what cluster size will we target?

**Comment by rootfs** [comment]
#365

**Comment by marceloamaral** [comment]
Initial performance analysis test is in #391.

**Comment by marceloamaral** [comment]
The PRs #381 and #392 are related to this issue.

**Comment by marceloamaral** [comment]
The PR #427 introduces a 2.4X performance improvement for Kepler regarding the CPU profiling.

**Comment by marceloamaral** [comment]
Closing this after we have introduced some performance improvements.
