### ISSUE TITLE
benchmark critical paths to ensure scalability and low cpu usage

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#382]
**Is your feature request related to a problem? Please describe.**
Kepler should stay low footprinted and scalable. Functions in tight loops or critical loops should be benchmarked. The benchmark are to be used to detect regressions

**Describe the solution you'd like**
The [collector.Update](https://github.com/sustainable-computing-io/kepler/blob/main/pkg/collector/metric_collector.go#L106) function runs in a tight loop. This is the main function that collects stats and builds metrics.

The [collector.Collect](https://github.com/sustainable-computing-io/kepler/blob/main/pkg/collector/metric_collector.go#L106) function is called each time the metric endpoint is scraped. This function should scale well regardless the number of metrics.

Both integration and benchmark tests should be developed.

**Comment by marceloamaral** [comment]
#366
