### ISSUE TITLE
Apply folder structure with standards layout

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/kepler#385]
details at https://github.com/golang-standards/project-layout/blob/master/README.md

**Comment by marceloamaral** [comment]
It's fine to deviate from the standard layout a bit, this is just a guideline for starting a project.

But suggestions to improve the layout are always welcome.

Which folders are you suggesting to change?

**Comment by marceloamaral** [comment]
@SamYuan1990 can we close this issue?
