### ISSUE TITLE
Provide Community Meeting Invite and Notes

### ISSUE THREAD

**Issue by wangchen615** [sustainable-computing-io/kepler#394]
**Is your feature request related to a problem? Please describe.**
We do not yet have a doc to share the community meeting info,  meeting notes, and meeting recordings on this GitHub.

**Describe the solution you'd like**
Provide a community meeting doc to include the above info.

**Describe alternatives you've considered**
Or provide the above info in the wiki page or documentation website.

**Comment by rootfs** [comment]
the meeting info is [here](https://github.com/sustainable-computing-io/kepler#community-meetings)

**Comment by rootfs** [comment]
@husky-parul would you mind posting the meeting info on kepler-doc?

**Comment by nikimanoledaki** [comment]
This could go under the new `Project` section on the docs website 😄
