### ISSUE TITLE
how to do ratio calculation correctly in local lr?

### ISSUE THREAD

**Issue by jichenjc** [sustainable-computing-io/kepler#424]
**Describe the bug**

1) question on containerNumber
containerNumber => this include system process, should we exclude it?

https://github.com/sustainable-computing-io/kepler/blob/main/pkg/model/estimator/local/ratio.go#L52

2) question on algorithm

as comment said `power = nodeResEnergyUtilization / containerNumber` is not a good way

should we consider cgroup data e.g the (cgroupfs_cpu_usage_us) / total?
```
cgroupfs_user_cpu_usage_us cgroupfs_ioread_bytes cgroupfs_iowrite_bytes cgroupfs_memory_usage_bytes cgroupfs_cpu_usage_us cgroupfs_system_cpu_usage_us
```

**Comment by marceloamaral** [comment]
Yes, `cgroupfs_cpu_usage_us` is a good metric candidate

**Comment by jichenjc** [comment]
ok, will see how we can improve here
