### ISSUE TITLE
[RFE] Correlate Pod and Intel ACC100 FEC power consumption

### ISSUE THREAD

**Issue by williamcaban** [sustainable-computing-io/kepler#44]
**Is your feature request related to a problem? Please describe.**
The Telco 5G RAN workloads have high power consumption. Today there is not a consistent way to collect these metrics to understand how much is the actual power consumption of these accelerators (e.g. Intel ACC100) based on the use of each Pod, and much less how it relates to the power consumption of a specialized CNF like the Distributed Unit (DU) workload.

**Describe the solution you'd like**
- Using metrics collected by [Intel ACC100 FEC](https://github.com/smart-edge-open/sriov-fec-operator/blob/4a309763e6148503f66058806b34bb6fcd7c67ac/sriov-fec/config/prometheus/monitor.yaml) and node-level information, correlate/map the power consumption of hardware accelerators (e.g. Intel ACC100) to the specific DU workloads using it, and how much of the power consumption each Pod represents.

**Additional context**
Intel Operator for Wireless FEC Accelerators
https://catalog.redhat.com/software/operators/detail/6001a748e4e3f23b0b6ad765

**Comment by rootfs** [comment]
The next iteration will plan a plugin model so that new HW metrics collector can be developed independently. Let's use AC100 FEC as our first plugin for the exercise.
