### ISSUE TITLE
containerIDToContainerInfo should be updated to reflect removed container?

### ISSUE THREAD

**Issue by jichenjc** [sustainable-computing-io/kepler#474]
**Describe the bug**

https://github.com/sustainable-computing-io/kepler/blob/main/pkg/cgroup/resolve_container.go#L56

seems this defined somewhere and updated when creation
seems no place to update it when pod got destroyed?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marceloamaral** [comment]
The PR #635 might improve this.

**Comment by sunya-ch** [comment]
Agree to @marceloamaral.
@jichenjc  Would you mind closing this issue?

**Comment by rootfs** [comment]
should be fixed in #635
