### ISSUE TITLE
why use dummy Impl of power component instead of estimated? 

### ISSUE THREAD

**Issue by jichenjc** [sustainable-computing-io/kepler#480]
**Is your feature request related to a problem? Please describe.**

we are using dummy if no RAPL or MSR 
https://github.com/sustainable-computing-io/kepler/blob/main/pkg/power/components/power.go#L60

but we do have estimated
https://github.com/sustainable-computing-io/kepler/blob/main/pkg/power/components/source/estimate.go

so from name, same estimated is suitable than dummy? 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jichenjc** [comment]
@marceloamaral do you know why we have use dummy? Thanks

**Comment by marceloamaral** [comment]
I think the dummy was created before for testing purposes.
If I remember correctly, the estimate needs to have the estimate sidecar, right?
Therefore, if we need to run a test without the estimated sidecar and the node does not support RAPL, the dummy will be used.

**Comment by jichenjc** [comment]
dummy is selected unconditionally 
let me see whether I can add a estimated logic here (first estimate then if not possible, use dummy)

**Comment by marceloamaral** [comment]
@jichenjc is this still a problem?

**Comment by jichenjc** [comment]
no, should be ok now
