### ISSUE TITLE
Export kepler_container_(resource usage metric) for model training

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler#495]
**Is your feature request related to a problem? Please describe.**

According to the metric list [here](https://sustainable-computing.io/design/metrics/#kepler-metrics-overview), there are only hardware counter metrics exported. 
We also need the other set of metrics to build the model that is available on the system that has no hardware counter.

**Describe the solution you'd like**

We can name it corresponding to what we define in the config/types.go and label with the source.
 
https://github.com/sustainable-computing-io/kepler/blob/20ccfe414b0329a6b14bb0c907c5be27b3c2aa71/pkg/config/types.go#L26-L45

**Track progress:** 
- [x] system features (cpu_architecture in `kepler_node_nodeInfo`, cpu_frequency in `kepler_node_cpu_scaling_frequency_hertz`)
- [x] kubelet features by https://github.com/sustainable-computing-io/kepler/pull/496
- [x] bpf (some done in https://github.com/sustainable-computing-io/kepler/pull/502, still need to change cpu_time to the same format with `_total`). Currently, it is `kepler_container_cpu_cpu_time_us`. https://github.com/sustainable-computing-io/kepler/pull/547
- [x] cGroups https://github.com/sustainable-computing-io/kepler/pull/547

Signed-off-by: Sunyanan Choochotkaew [sunyanan.choochotkaew1@ibm.com](mailto:sunyanan.choochotkaew1@ibm.com)

**Comment by jichenjc** [comment]
so you just want to expose all those metrics listed above ? if so I can give a try if no one else is working on it

**Comment by sunya-ch** [comment]
> so you just want to expose all those metrics listed above ? if so I can give a try if no one else is working on it

Yes, I would like to have all metrics available if it is enabled. They would be enabled only in the system that can and want to contribute on building the model in an online manner. 

I would very appreciate your help :D

**Comment by sunya-ch** [comment]
@jichenjc  will you also work on cgroup metrics? Otherwise, I will work on that. I need those metrics for refactoring the kepler-model-server training pipeline?

**Comment by jichenjc** [comment]
>>.will you also work on cgroup metrics? Otherwise, I will work on that. I need those metrics for refactoring the kepler-model-server training pipeline?

yes, please ,I just return back from holiday so please submit PR thus I won't block your progress.. thanks~

**Comment by KaiyiLiu1234** [comment]
Could you change it so that kepler_container_cpu_cpu_time_us is instead kepler_container_cpu_time_total (remove the extra cpu)?

**Comment by sunya-ch** [comment]
> Could you change it so that kepler_container_cpu_cpu_time_us is instead kepler_container_cpu_time_total (remove the extra cpu)?

update to `kepler_container_bpf_cpu_time_us_total`. Please review this PR https://github.com/sustainable-computing-io/kepler/pull/547.
