### ISSUE TITLE
idea: present Kepler on eCHO Livestream

### ISSUE THREAD

**Issue by lizrice** [sustainable-computing-io/kepler#497]
I'm one of the hosts of a weekly livestream about eBPF technology, called [eCHO](https://youtube.com/playlist?list=PLDg_GiBbAx-mY3VFLPbLHcxo6wUjejAOC). I think Kepler would make a really great topic for an episode. Is there someone who would like to come and show it to our audience?

**Comment by rootfs** [comment]
Thank you for the invitation @lizrice! I have watched quite some episodes. I am excited to join your show. It will be great news for Kepler and eBPF community on the show.

**Comment by lizrice** [comment]
Brilliant! I reached out to you with a message on LinkedIn so we can co-ordinate a date

**Comment by lizrice** [comment]
Done in [Episode 80](https://www.youtube.com/live/xzfTU_Wa7rU?feature=share)
