### ISSUE TITLE
make cluster-up and sync available to more use cases

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#507]
create a dedicated artifact or repo for make cluster-up and integrate with CI

**Comment by rootfs** [comment]
1) simple way to clone/retrieve the artifact
2) kepler repo: make cluster-up and get the repo

**Comment by SamYuan1990** [comment]
> * simple way to clone/retrieve the artifact

wait.... you mean bcc?

**Comment by SamYuan1990** [comment]
@rootfs , @marceloamaral I suppose we don't need to add bcc as a part of this ticket scope. as we don't own bcc. and our bcc deb packages, well, just for ubuntu OS. which means even if we implemented  **a simple way to clone/retrieve the artifact** client still need to make their bcc libs.

**Comment by SamYuan1990** [comment]
for kepler repo and kepler action repo, @rootfs , @marceloamaral `git submodule` or just clone during make script running? which way do you prefer?

**Comment by rootfs** [comment]
@SamYuan1990 right, bcc is not a requirement. The cluster-up and sync are needed.
