### ISSUE TITLE
package Kepler for standalone distribution

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#515]
**Is your feature request related to a problem? Please describe.**
Kepler is distributed in a container for Kubernetes. However, when deployed in a standalone and non-containerized environment, a software packaging scheme, rpm or deb, is needed.

**Describe the solution you'd like**
Initially a Kepler rpm should be supported

**Comment by rootfs** [comment]
Using Github Action to create the rpm and hosting the manifests there is a good start.

**Comment by SamYuan1990** [comment]
personally, binary is good enough and upload binaries to release page?
https://github.com/prometheus/node_exporter/releases/tag/v1.5.0
for systemd we may able to ref https://github.com/prometheus/node_exporter/tree/master/examples/systemd

**Comment by SamYuan1990** [comment]
We just have a binary for kepler as release which is good enough right?
if we provide a systemd job, do we need root privileges for `/proc` access? or we need root privileges to open network so that this systemd job able to listen on port as 9102?a
if my point of view a binary release is a minimum size of standalone. A systemd job contains more features as start, stop, auto recover, log, privileges etc.

**Comment by husky-parul** [comment]
> We just have a binary for kepler as release which is good enough right? if we provide a systemd job, do we need root privileges for `/proc` access? or we need root privileges to open network so that this systemd job able to listen on port as 9102?a if my point of view a binary release is a minimum size of standalone. A systemd job contains more features as start, stop, auto recover, log, privileges etc.

We are starting with rpm binary. Wanted to clarify if we intend to support start/stop/log etc.

**Comment by SamYuan1990** [comment]
Pre offline discussion with @rootfs
@husky-parul I am good if we can put binary in release page and rpm package on any rpm package center.

**Comment by Stef16Robbe** [comment]
Are there any plans of supporting other packaging formats like .deb?
