### ISSUE TITLE
Use github.com/VictoriaMetrics/metrics instead of github.com/prometheus/client_golang

### ISSUE THREAD

**Issue by valyala** [sustainable-computing-io/kepler#619]
**Is your feature request related to a problem? Please describe.**

Kepler uses `github.com/prometheus/client_golang` library for metrics' exposition. This library provides non-trivial to use bAPI with many features, which aren't used by Kepler.

**Describe the solution you'd like**

To use [github.com/VictoriaMetrics/metrics](https://github.com/VictoriaMetrics/metrics) library instead. It provides [much easier to use API](http://godoc.org/github.com/VictoriaMetrics/metrics). It also supports the ability to push metrics additionally to exporting the metrics for pulling. The metrics' push may be useful when metrics are collected from secure environments without external access.

**Comment by rootfs** [comment]
@valyala thanks for sharing your work. Please follow our prometheus client [discussion](https://github.com/sustainable-computing-io/kepler/discussions/439) here.
