### ISSUE TITLE
cgroup: use lxcfs to get 

### ISSUE THREAD

**Issue by jichenjc** [sustainable-computing-io/kepler#625]
looks like we are using host /proc mount to container /proc now 
https://github.com/sustainable-computing-io/kepler/blob/main/manifests/config/exporter/exporter.yaml#L100
but not sure it's a recommended way to do so in container world?

seems there are https://github.com/lxc/lxcfs and can provide host info 
not sure this has been discussed before or not ..

NOTE: not expert in this area, so raise question to see whether anyone has any insight

**Comment by marceloamaral** [comment]
>looks like we are using host /proc mount to container /proc now

@jichenjc Since the beginning, the code has relied on inspecting the file `/proc/$pid/cgroup` to obtain the container ID. Also note that the containerd cgroup library also requires access to this file.

Btw, could you give an example of what we could do with `lxcfs`?
