### ISSUE TITLE
command cannot be displayed normally

### ISSUE THREAD

**Issue by LeiZhou-97** [sustainable-computing-io/kepler#638]
**Describe the bug**
 
Right now, there is a command length limit (len=10). If the length of command larger than 10, cuts it.
`kepler_container_package_joules_total{command="redis-serv", container_name="redis", container_namespace="default", mode="dynamic", pod_name="ei-redis-deployment-59b8dd9476-lv89k"} `

**Expected behavior**

command="redis-server"

Could we remove the length limitation, split the command string directly, and use the first string after splitting?

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootfs** [comment]
@LeiZhou-97 unfortunately, the command line length is fixed in kernel. Getting the entire cmdline needs to parse the /proc/pid/cmdline. This could add overheads in reading files as well as in exporting metrics.

**Comment by LeiZhou-97** [comment]
@rootfs got it, thanks for the explanation!
