### ISSUE TITLE
manage metrics exposure

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#669]
Currently kepler metrics consists of end user oriented (energy) and developer oriented metrics (bpf, cgroup, etc). We need to have a mechanism to decide which to expose based on end user and scalability requirements

**Comment by jichenjc** [comment]
>>>which to expose based on end user and scalability requirements

I think we have a lot of config options for now (something like ENABLE_XXXX etc) , maybe during create manifests/operator
we set a config to dev and/or operator so we can use it to decide what ENABLE_XXX is enable/disable?

**Comment by SamYuan1990** [comment]
we can open those flags to user, to enable or disable some metrics.
but what's the default option/approach for us?

**Comment by rootfs** [comment]
enabled now
![image](https://github.com/sustainable-computing-io/kepler/assets/7062400/bb01c581-61bf-471b-8194-a38ecd401d53)

**Comment by jichenjc** [comment]
I didn't see any PR related to this ... so is the close on purpose?
