### ISSUE TITLE
Support CPU time based ratio model

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#672]
**Is your feature request related to a problem? Please describe.**
Current HW counter (i.e. cpu instruction/cycles/cache misses) based power models need to read perf counters with some overhead.  Using cpu time as usage metric can help reduce these overhead.

**Describe the solution you'd like**
An option to use cpu time as usage metric.

**Comment by jichenjc** [comment]
>>>Using cpu time as usage metric can help reduce these overhead.

I was told that eBPF is accurate than CPU time and we prefer HW counter
so we are tradeoff between overhead and data/model accurancy.. not sure with CPU time we get `good enough` data? 
@rootfs

**Comment by alysondeives** [comment]
Hi @rootfs, this would be great to reduce the overhead on rt kernels!
