### ISSUE TITLE
Add SBOM to release

### ISSUE THREAD

**Issue by bradmccoydev** [sustainable-computing-io/kepler#685]
**Is your feature request related to a problem? Please describe.**
Currently, we do not have an SBOM attached to the release of Kepler. Having one attached will help us identify what components we have if there was a vulnerability in one and also help adopters with securing their software supply chain.

A software bill of materials (SBOM).  is a list of all the open-source and third-party components present in a codebase. An SBOM also lists the licenses that govern those components, the versions of the components used in the codebase, and their patch status, which allows security teams to quickly identify any associated security or license risks.

**Describe the solution you'd like**
We can easily put an additional step on the release.yml to attach the SBOM to the release, not changing or breaking anything.

I'm happy to do this work.

**Comment by jichenjc** [comment]
@bradmccoydev thanks , assigned to you just now

@marceloamaral @rootfs FYI a good improvement to kepler

**Comment by marceloamaral** [comment]
@bradmccoydev and @jichenjc sounds like a good plan!

It is also important to establish some recommendations for defining the best way to handle code updates.

**Comment by SamYuan1990** [comment]
Cool!
is there any SBOM which able to support both docker/container and binary?

**Comment by bradmccoydev** [comment]
Hello, I have finished my testing on this and it worked fine. I have made the PR
