### ISSUE TITLE
docs: Prometheus service monitors does not exist

### ISSUE THREAD

**Issue by agardnerIT** [sustainable-computing-io/kepler#701]
**Describe the bug**
This is not a Kepler bug but more a docs / usability bug.

Following the installation page, I install Kepler and the pod starts:

```
# kubectl -n epler get pods
kepler-49dcf   1/1     Running   0          3m22s
```

So far, so good.

Now I follow the instructions to install Prometheus:

1) There are `#` in front of these commands. Not a big deal, but for consistency with the previous `helm` commands, I suggest either using or don't, but don't switch halfway down the page.

Anyway:

```
git clone https://github.com/prometheus-operator/kube-prometheus
cd cube-prometheus
kubectl apply --server-side -f manifests/setup
```

Again, all good up to here.

Now the issue:

```
% until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done
No resources found
```

So I don't know if I can continue or not...

Happy to create a PR if you can hint as to the fix.

**Comment by rootfs** [comment]
@agardnerIT `No resources found` is expected, there is no servicemonitor yet. The wait is to check if the resource api is created but doesn't expect the resource is there. Please create a doc PR to explain this expected behavior, thanks.
