### ISSUE TITLE
not report newly deployed pod metrics

### ISSUE THREAD

**Issue by jichenjc** [sustainable-computing-io/kepler#703]
**Describe the bug**

reported this before, but seems still exist with latest code 

created pod and wait for 15 min
```
# kubectl get po -n default
NAME                               READY   STATUS    RESTARTS   AGE
nginx-deployment-cbdccf466-glkdv   1/1     Running   0          15m
nginx-deployment-cbdccf466-xv8zz   1/1     Running   0          15m
```

but the pod is not reported in metrics at all..
```
# curl localhost:9102/metrics | grep kepler_container_package_joules_total | grep nginx
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  107k    0  107k    0     0  54.5M      0 --:--:-- --:--:-- --:--:--  105M
(base) [root@lozlp51 ~]#
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marceloamaral** [comment]
There is a bug, that if a container is starting, the pod might not have the container ID yet. But if  a pod is wrongly identified as system process, it will never be fixed later. The apiserver PR (#635) fix this.

**Comment by jichenjc** [comment]
not sure someone already verified this ? if anyone did and it works fine , I think we can close this 
if not , I will try to do some test on it?

**Comment by jichenjc** [comment]
did a quick test with new deployed pod , I can see those reported after a few seconds, so closing this issue
thanks @marceloamaral
