### ISSUE TITLE
project description does not match the architecture 

### ISSUE THREAD

**Issue by cathyhongzhang** [sustainable-computing-io/kepler#710]
**Describe the bug**
The project description says: Kepler (Kubernetes Efficient Power Level Exporter) uses eBPF to probe energy-related system stats and exports them as Prometheus metrics. But the architecture diagram shows that eBPF only probes performance counter stats and it is the Energy Stats Reader that probes energy-related stats. An update/clarification is needed for better alignment and for people to understand the project better

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootfs** [comment]
Thank you @cathyhongzhang for reading into these. The project description is updated 
```
Kepler (Kubernetes-based Efficient Power Level Exporter) uses eBPF to probe performance counters and other system stats, use ML models to estimate workload energy consumption based on these stats, and exports them as Prometheus metrics
```

Please let me know you have any questions.
