### ISSUE TITLE
Calendar invite for biWeekly in the Readme is not working

### ISSUE THREAD

**Issue by nttDamien** [sustainable-computing-io/kepler#713]
**Describe the bug**
Imported the iCal in outlook to attend the biweekly, but no meeting appeared...

**To Reproduce**
1. open outlook online,
2. Drap and drop the .ics file
3. check different Tuesdays for the meeting

**Expected behavior**
a biweekly meeting on Tuesday appears with zoom call id to join

**Desktop (please complete the following information):**
 - OS Windows 11, Chrome 113.0.5672.127 

**Additional context**
Also tried on Android: "unable to launch event" error
Looked in the iCal, there is some info (NY time), but it seems to be missing the zoom call details at least.

**Comment by rootfs** [comment]
The previous community meeting calendar ended. We will move to new schedules starting in the middle of June. Stay tuned!

**Comment by rootfs** [comment]
@nttDamien the new meeting calendar is posted 
https://github.com/sustainable-computing-io/kepler/pull/720

**Comment by rootfs** [comment]
The zoom meeting is migrating to CNCF zoom. Please check the info [here ](https://github.com/sustainable-computing-io/community/blob/main/community-event.md)

@nttDamien

**Comment by nttDamien** [comment]
@rootfs thanks a lot for pinging me on this. I'll update !
