### ISSUE TITLE
kepler-action with tag

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#723]
we should add tag for kepler action as a long term goal.
https://github.com/sustainable-computing-io/kepler-helm-chart/pull/28#issuecomment-1556215845

our pain points for today as:
- there are only one or two people understand how our CI works today.
- we have strong dependency with github action agent.

For short term:
- Make our 1st try with tag for CI.
- create v0.0.0 tag for CI related repos, base on today's code(which works). 
   - [x] for local-dev-cluster
   - [ ] for kepler action
- [x] #730

Hence, we'd better considering with changes following as long term to get more maintainers know our CI logic:
- [x] add CI related discussion in project plan meeting and bi weekly sync up session.
- [ ] document related changes for maintainers.
    - [x] rfc(#717 )

- [ ] document related changes for user.
    - [x] https://github.com/sustainable-computing-io/local-dev-cluster/issues/16

Start new CI development lifecycle to resolve with major features to reduce risk/impact as github action agent's release to us:
1. version control for each components for example kubectl, kind, kind image.
2. other platform supports for example, mircoshift support.(#182 )
3. update kepler action CI to metric based, to test new version of kubectl, kind, kind image. And how they are integrated with github action agent, Hence we can by trigger a job, to get know which version is workable.(aline with github action agent)

ref two example which breaks our CI:
A. github action agent upgrade, some network tips updated for container runtime. we updated kind version to fix it.
B. github action agent upgrade with their own kernel, conflicts with our hard code. we fixed up in code.

**Comment by SamYuan1990** [comment]
update ticket to make it reflect item status.
