### ISSUE TITLE
Provide go vet and gosec in Github action

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#724]
**Is your feature request related to a problem? Please describe.**
Use go vet and gosec to ensure the code is following the best practice with security check

**Comment by rootfs** [comment]
Per @marceloamaral https://pkg.go.dev/github.com/ossf/scorecard/v2#section-readme

**Comment by sbdtu5498** [comment]
/assign
@rootfs will do it.

**Comment by SamYuan1990** [comment]
https://github.com/sustainable-computing-io/kepler/blob/main/.golangci.yml#L49
please double check if go vet is covered in current golangci or not.

**Comment by SamYuan1990** [comment]
also https://github.com/sustainable-computing-io/kepler/blob/f7d6dbd2d3980dba10dd19b554631a32849ed104/Makefile#L207 test script.

**Comment by sbdtu5498** [comment]
> https://github.com/sustainable-computing-io/kepler/blob/main/.golangci.yml#L49
please double check if go vet is covered in current golangci or not.

It is covered in the current .golangci-lint

**Comment by sbdtu5498** [comment]
@SamYuan1990 the reason behind addding govet ghaction is visibility. golangcilint has like this many message related to different linting violations or warnings
```
$ golangci-lint run --out-format json | jq '.Issues | length'
50

```So, while it's good to let it be there but differentiating outputs would be difficult for a beginner. So I think it would be a good idea to have dedicated govet action. Does it makes sense.

**Comment by SamYuan1990** [comment]
> We should not have duplications. If we're moving it to a GitHub Action, we should remove it from the other tests.

we should not have duplications.
hence another two questions comes are
- if we implement in golangci-lint why we have duplicate implementations?
- if we implement in go vet, but as golangci-lint able to run/cover go vet... why we have different limitations ?

golangcilint covers many static scan rules of code, as a single command to cover everything which is great isn't it?
the beginner also can learn form other static scan/lint rules, which benefits for them right? @sbdtu5498

**Comment by sbdtu5498** [comment]
> > We should not have duplications. If we're moving it to a GitHub Action, we should remove it from the other tests.
> 
> we should not have duplications. hence another two questions comes are
> 
> * if we implement in golangci-lint why we have duplicate implementations?
> * if we implement in go vet, but as golangci-lint able to run/cover go vet... why we have different limitations ?
> 
> golangcilint covers many static scan rules of code, as a single command to cover everything which is great isn't it? the beginner also can learn form other static scan/lint rules, which benefits for them right? @sbdtu5498

As you say that golangci-lint covers a lot of tests and that's a positive remark, but at the same time, it makes it a bit difficult for anyone to understand the lining results as it has lots of other forms of error. Any standard linting steps in my opinion should be implemented independently and we should use golangci-lint just to provide a unified way to run all the lints. Adding them in CI two times, doesn't makes much difference either. But the point being use of CI and its visibility should be loud and clear to all the stakeholders.
