### ISSUE TITLE
Kepler Documentation

### ISSUE THREAD

**Issue by husky-parul** [sustainable-computing-io/kepler#75]
**Describe the solution you'd like**
Add documentation on:

- About Kepler
- Describe the modules, bpf, model server, collector, power, attacher etc
- Run on Kubernetes
- Run on OpenShift
- Run locally

[Doc repo]( https://github.com/sustainable-computing-io/kepler-doc)

**Comment by husky-parul** [comment]
We can use one of these as a reference
[Volsync](https://volsync.readthedocs.io/en/stable/)
[Microshift](https://microshift.io/)

**Comment by husky-parul** [comment]
@rootfs Please assign the issue to me. For some reason I still can't assign issues to myself.

**Comment by husky-parul** [comment]
@rootfs @nikimanoledaki @williamcaban I would appreciate your inputs on which docs would look good for Kepler. I have mentioned two references above. My preference is VolSync. It looks simple, intuitive and easy to navigate.

**Comment by williamcaban** [comment]
I guess you mean using the [Sphinx](https://www.sphinx-doc.org/) theme. That's fine with me. I'm happy with anything that can use markdown-type files for quick iteration and easier collaboration on docs.

**Comment by rootfs** [comment]
Please use [this repo](https://github.com/sustainable-computing-io/kepler-doc) for documentation. Ideally we have doc to serve the following purposes:
- For developers: an deep dive into the development environment, architecture, methodology, enhancement.
- For end users:  Environment requirement, deployment process, dashboard setup and customization. 
- For integrators: Packaging, API, and extensions.

**Comment by husky-parul** [comment]
I am going to follow the this flow

## Contents
### Overview
### Installation
#### Kubernetes
#### OpenShift
###  Usage
#### Developers
#### End Users
#### Integratiors

**Comment by geertpingen** [comment]
Hi, checking out this project after Kubecon EU. Im currently using [Scaphandre](https://github.com/hubblo-org/scaphandre), and scanning for alternatives.

Im looking for documentation on what exactly it is you're monitoring, and how you are calculating that, similar to:
https://github.com/hubblo-org/scaphandre/blob/main/docs_src/explanations/how-scaph-computes-per-process-power-consumption.md. Then I noticed this issue, so I would recommend having a section like that in your docs. As a user this is the first thing Im looking for.

**Comment by husky-parul** [comment]
Thanks @geertpingen for your suggestions. We are still in early stages but to give some context, we calculate power consumption of running containers in Kubernetes env based on cpu cycles/instruction/time/cache misses etc. Incorporating the details on how it is calculates is still WIP and will be available at our docs page [here](https://sustainable-computing-io.github.io/kepler-doc/)

**Comment by rootfs** [comment]
@geertpingen thanks for the pointer, alternative is good for consumers :D 

Kepler and Scaphandre both want to give users an answer on how much energy spent by a workload (process, container, or VM). 

The difference is that, Scaphandre spends a good deal on breaking down the processes' CPU time to attribute the energy to the workloads. Kepler uses CPU time as well as CPU spends time on doing. At the end of the day, not all CPU instruction consumes the same amount of energy.

**Comment by geertpingen** [comment]
@husky-parul  @rootfs Thanks for the quick replies! Perhaps this is a question best asked in another setting (are you active on Slack or a similar platform?), but I was wondering how you obtain the coefficients here:
https://github.com/sustainable-computing-io/kepler/blob/a71dce95c1e76d1866f417c1ec8fbf20b58403fe/pkg/model/model.go#L47 (used at https://github.com/sustainable-computing-io/kepler/blob/79055d74185b9fad19dc974e6f65312f453ae72c/pkg/collector/reader.go#L320)

**Comment by rootfs** [comment]
@geertpingen slack invite sent. The coefficients are hardcoded at the moment. They will be learned via online training by the model server (still under construction). If you are excited about building a model of your own, [it is a place](https://github.com/sustainable-computing-io/kepler-model-server) for collaboration
