### ISSUE TITLE
integration test: build manifest doesn't build with correct image name

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler#784]
### What happened?

On integration test according to this commit https://github.com/sustainable-computing-io/kepler/commit/a94cee02af53da0134da52c92b59e985b9378aeb, the manifest deployed in the cluster to test is using official image not the locally-built image. 

### What did you expect to happen?

Need to set env for building manifest using image from local registry with dev tag.

### How can we reproduce it (as minimally and precisely as possible)?

Run integration_test CI

### Kepler image tag

<details>

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider or bare metal

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by rootfs** [comment]
fixed in #785
