### ISSUE TITLE
Add changelog with every Kepler releases

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/kepler#789]
### What would you like to be added?

Having CHANGELOG added to the Kepler repo

### Why is this needed?

Currently, we don't have any changelog provided with any Kepler release. This makes it very difficult to keep track of what's been added/changed/any bug fixed etc. to the released version. Having a changelog makes it super easy to record all these changes that went into a release and makes it easy to spot the difference between the different releases.

**Comment by jichenjc** [comment]
my experience in other projects is if we use github to auto create release and for each significant change need a RELEASE NOTE
https://github.com/kubernetes/cloud-provider-openstack/blob/master/.github/PULL_REQUEST_TEMPLATE.md

then something like those notes will be generated as change log automatically..
https://github.com/kubernetes/cloud-provider-openstack/releases/tag/v1.25.6

@SamYuan1990 FYI
