### ISSUE TITLE
libbpf integration failed

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler#802]
### What happened?

There is frequent failure in integration test of libbpf: https://github.com/sustainable-computing-io/kepler/actions/workflows/integration_test_libbpf.yml at healthz logic. 

I also did the integration test locally here https://github.com/sunya-ch/kepler/actions/runs/5598480773 but not sure what makes difference. 

### What did you expect to happen?

pass the test

### How can we reproduce it (as minimally and precisely as possible)?

run integration test

### Kepler image tag

<details>

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider or bare metal

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jiere** [comment]
@sunya-ch , I find that your local forked repo's GHA ymls are too old, could you please rebase to kepler:main  latest and have more tries?

Also, please look at the latest run pass [job](https://github.com/sustainable-computing-io/kepler/actions/runs/5611502503) which triggered by @rootfs's new PR.

Let's check if such failure jobs were transient ones?

**Comment by rootfs** [comment]
this looks no more an issue now
