### ISSUE TITLE
kepler tracks the all of k8s pods

### ISSUE THREAD

**Issue by Lai-Kenny** [sustainable-computing-io/kepler#806]
### What would you like to be added?

Hello, everyone, I have a question about the kepler tracks the all of k8s pods.
Because I need to change docker image and restart pod or I deploy the new pod.

### Why is this needed?

I'm asking this because I have to make sure Kepler stays on all the time.
Many thanks.

**Comment by rootfs** [comment]
@Lai-Kenny do you mean changing kepler image? Kepler will restart and re-collect data after changing image. But if you also Prometheus, kepler metrics should be persisted there, you can still see continuous flow on your dashboard.
