### ISSUE TITLE
Should have cluster cleanup job in e2e test. 

### ISSUE THREAD

**Issue by jiere** [sustainable-computing-io/kepler#814]
### What would you like to be added?

Current Kepler e2e integration test has no cleanup job, so after test, both the cloud-provider cluster and the kepler daemonset remain on the runner.

When new CI jobs are scheduled to the same runner, the cluster setup job will fail, still use the earlier cluster to run test, this may bring side effect.

See job error logs [example](https://github.com/jiere/kepler/actions/runs/5583266592/job/15120269564#step:6:567).

### Why is this needed?

Add cluster cleanup job in GHA e2e test workflow, since both Kind and microshift have supported the cluster-down ops in local-dev-cluster.

**Comment by marceloamaral** [comment]
Good point, the scripts is actually missing the `make cluster down`
We had it before and should have it back again.
