### ISSUE TITLE
make: *** No rule to make target 'build_rpm'.

### ISSUE THREAD

**Issue by husky-parul** [sustainable-computing-io/kepler#818]
### What happened?

The Release workflow is failing with the error
```
make: *** No rule to make target 'build_rpm'.
```

### What did you expect to happen?

rpm to be built

### How can we reproduce it (as minimally and precisely as possible)?

Run Release action 
https://github.com/sustainable-computing-io/kepler/actions/runs/5624147749

### Anything else we need to know?

Logs https://github.com/sustainable-computing-io/kepler/actions/runs/5624147749/job/15241670847

### Kepler image tag

<details>
latest
</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider or bare metal

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jichenjc** [comment]
I tried locally seems same result 

```
[root@jitest42 kepler]# make containerized_build_rpm
/bin/podman run --rm \
        -v /root/kepler/bpfassets/libbpf:/kepler:Z -w /kepler -v /root/kepler/bpfassets/libbpf/_output/rpmbuild:/root/rpmbuild \
        -e _VERSION_= -e _RELEASE_= -e _ARCH_= \
        -e _TIMESTAMP_="Mon Jul 24 05:27:49 UTC 2023" -e _COMMITTER_= -e  _CHANGELOG_= \
        -e GOROOT=/usr/local/go -e PATH=/usr/share/Modules/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/go/bin:./test-bin:/usr/local/go/bin \
        quay.io/sustainable_computing_io/kepler_builder:ubi-8.6-bcc-0.24-go1.18 \
        make build_rpm
make: *** No rule to make target 'build_rpm'.  Stop.
make: *** [Makefile:232: containerized_build_rpm] Error 2

```
