### ISSUE TITLE
Changing KEPLER_LOG_LEVEL after deployment

### ISSUE THREAD

**Issue by davidszegedi** [sustainable-computing-io/kepler#821]
### What would you like to be added?

Currently, the KEPLER_LOG_LEVEL value in kepler-cfm configmap can only be changed during the manifests build phase, with the DEBUG_DEPLOY option.
For troubleshooting purposes, It would be more convenient to have the ability to edit KEPLER_LOG_LEVEL directly in the kepler-cfm configmap after deployment of the kepler-exporter daemonset, then restart kepler-exporter pods to get more verbosity in the logs, and update the documentation accordingly.

### Why is this needed?

Based on kepler deployment experience on the field, the default verbosity of kepler-exporter pods is usually not sufficient to do proper troubleshooting, and even though re-generating manifests is not very long, most customers would rather just edit the configmap then restart pods to reflect changes instead of re-deploying manifests.

**Comment by trent-s** [comment]
Thank you for reporting this. I am taking a look at how to implement this.

**Comment by trent-s** [comment]
Bump.
