### ISSUE TITLE
Verify energy accuracy

### ISSUE THREAD

**Issue by tobby-yuan** [sustainable-computing-io/kepler#857]
### Which document would you like to be mentioned?

Hello everyone, I want to ask two questions.
1. Which model will be use for energy estimation if I only deploy [kepler using helm chart](https://github.com/sustainable-computing-io/kepler-helm-chart)?
2.  Is there any theorem or paper supporting this model can be used for energy estimation?

### Why is this needed?

I want to know the accuracy of energy estimation.

**Comment by jichenjc** [comment]
@rootfs @marceloamaral I believe you have a set of papers about the model , maybe you can share or put into README (seems not yet?)

**Comment by tobby-yuan** [comment]
@rootfs @marceloamaral @jichenjc Would you already put a set of papers about the model into README ?
