### ISSUE TITLE
Starting kepler rpm issues "cannot attach kprobe, probe entry may not exist" message

### ISSUE THREAD

**Issue by aspanner** [sustainable-computing-io/kepler#861]
### What happened?

rpm eleast 0.5.3 installed
starting kepler on the CLI or via systemctl start kepler show the same error message:

kepler.service - Kepler
     Loaded: loaded (/usr/lib/systemd/system/kepler.service; disabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Fri 2023-08-11 13:14:18 AEST; 1 day 1h ago
   Main PID: 254003 (kepler)
      Tasks: 12 (limit: 38092)
     Memory: 72.7M
        CPU: 20.917s
     CGroup: /system.slice/kepler.service
             └─254003 kepler

Aug 11 13:14:18 y1 kepler[254003]: arch/x86/include/asm/ibt.h:78:8: warning: 'nocf_check' attribute ignored; use -fcf-protection to enable the attribute [-Wignored-attributes]
Aug 11 13:14:18 y1 kepler[254003]: extern __noendbr void ibt_restore(u64 save);
Aug 11 13:14:18 y1 kepler[254003]:        ^
Aug 11 13:14:18 y1 kepler[254003]: arch/x86/include/asm/ibt.h:32:34: note: expanded from macro '__noendbr'
Aug 11 13:14:18 y1 kepler[254003]: #define __noendbr       __attribute__((nocf_check))
Aug 11 13:14:18 y1 kepler[254003]:                                        ^
Aug 11 13:14:19 y1 kepler[254003]: 2 warnings generated.
Aug 11 13:14:19 y1 kepler[254003]: cannot attach kprobe, probe entry may not exist
Aug 11 13:14:19 y1 kepler[254003]: I0811 13:14:19.320129  254003 bcc_attacher.go:186] Successfully load eBPF module from bcc with option: [-DMAP_SIZE=10240 -DNUM_CPUS=8 -DSET_GROUP_ID]
Aug 11 13:14:19 y1 kepler[254003]: I0811 13:14:19.320393  254003 exporter.go:251] Started Kepler in 846.78589ms

### What did you expect to happen?

I expected to not see an issues attacking a kernel probe, as I am expecting this is fundamental to get power metrics.

### How can we reproduce it (as minimally and precisely as possible)?

Follow the kepler rpm installation instructions, use release 0.5.3 and start kepler either via cli or systemctl start kepler

### Anything else we need to know?

localhost:8888/metrics is showing metrics.

# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 1.676e-05
go_gc_duration_seconds{quantile="0.25"} 2.9869e-05
go_gc_duration_seconds{quantile="0.5"} 4.697e-05
go_gc_duration_seconds{quantile="0.75"} 6.5199e-05
go_gc_duration_seconds{quantile="1"} 0.001010315
go_gc_duration_seconds_sum 0.045946091
go_gc_duration_seconds_count 930
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 139
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.18.1"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 5.898624e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 2.086199544e+09
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.528293e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 2.3230602e+07
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 5.3818e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 5.898624e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 1.1337728e+07
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 8.192e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 62320
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 1.0387456e+07

...

kepler_process_uncore_joules_total{command="xembedsnip",mode="dynamic",pid="7892"} 0.003
kepler_process_uncore_joules_total{command="xembedsnip",mode="idle",pid="7892"} 0
kepler_process_uncore_joules_total{command="zsh",mode="dynamic",pid="138872"} 0.002
kepler_process_uncore_joules_total{command="zsh",mode="dynamic",pid="143930"} 0.003
kepler_process_uncore_joules_total{command="zsh",mode="dynamic",pid="18600"} 0.003
kepler_process_uncore_joules_total{command="zsh",mode="dynamic",pid="225538"} 0.003
kepler_process_uncore_joules_total{command="zsh",mode="dynamic",pid="227774"} 0.002
kepler_process_uncore_joules_total{command="zsh",mode="idle",pid="138872"} 0
kepler_process_uncore_joules_total{command="zsh",mode="idle",pid="143930"} 0
kepler_process_uncore_joules_total{command="zsh",mode="idle",pid="18600"} 0
kepler_process_uncore_joules_total{command="zsh",mode="idle",pid="225538"} 0
kepler_process_uncore_joules_total{command="zsh",mode="idle",pid="227774"} 0
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 21.78
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 25
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.77455104e+08
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.69172365803e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.833132032e+09
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes 1.8446744073709552e+19
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 3
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0

### Kepler image tag

<details>
release 0.5.3 rpm
</details>

### Kubernetes version

n/a

### Cloud provider or bare metal

Thinkpad X1 Yoga

❯ neofetch
             .',;::::;,'.                redhat@y1
         .';:cccccccccccc:;,.            ---------
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 38 (Workstation Edition) x86_64
    .:cccccccccccccccccccccccccc:.       Host: 20Y0S63N00 ThinkPad X1 Yoga Gen 6
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 6.3.11-200.fc38.x86_64
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 4 days, 19 hours, 18 mins
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 3426 (rpm), 25 (flatpak), 16 (snap)
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: zsh 5.9
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 1920x1200, 2560x1440
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: Plasma 5.27.6
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: KWin
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   Theme: [Plasma], Breeze [GTK2/3]
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Icons: [Plasma], breeze-dark [GTK2/3]
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Terminal: WezTerm
cccccc;dNMWXXXWM0::cccccccccccccc:,      CPU: 11th Gen Intel i7-1185G7 (8) @ 4.800GHz
cccccccc;.:odl:.;cccccccccccccc:,.       GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics]
:cccccccccccccccccccccccccccc:'.         Memory: 19494MiB / 31787MiB

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
❯ cat /etc/redhat-release
Fedora release 38 (Thirty Eight)

# paste output here
$ uname -a
❯ uname -a
Linux y1 6.3.11-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Jul  2 13:17:31 UTC 2023 x86_64 GNU/Linux
# paste output here
```
</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here
no command arguments used
</details>

### Container runtime (CRI) and version (if applicable)

<details>
n/a
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
n/a
</details>

**Comment by rootfs** [comment]
@aspanner isn't it the same as #847

**Comment by jichenjc** [comment]
yes, `rpm eleast 0.5.3 installed` doesn't have #847 log
I think this warning can be ignored, any functional impact you saw?
