### ISSUE TITLE
metric label submitted to estimator and to prometheus are mismatch

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler#870]
### What happened?

According to the issue in Kepler Model Server https://github.com/sustainable-computing-io/kepler-model-server/issues/116, it  has found that the some metrics (irq and cpu time) submitted to the estimator are mismatch from what exported to the prometheus. 

### What did you expect to happen?

It should be matched to what we trained the model.

### How can we reproduce it (as minimally and precisely as possible)?

enable estimator sidecar

### Kepler image tag

<details>
targeting v0.6
</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider or bare metal

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by vimalk78** [comment]
@sunya-ch is this issue closed?
