### ISSUE TITLE
Document why metrics in some namespaces in K8S cluster disappears after kepler is updated.

### ISSUE THREAD

**Issue by jiangphcn** [sustainable-computing-io/kepler#890]
### Which document would you like to be mentioned?

After kepler is updated, I found that metrics in some namespace in K8S cluster disappears. I think that it is good for user to know how to enable it again. Do we have best practice or these best practice was documented already.

### Why is this needed?

Missing metrics for these namespace is must-have to resolve.

**Comment by jichenjc** [comment]
>>>After kepler is updated, I found that metrics in some namespace in K8S cluster disappears. 

do you have any capture screen about it ?
