### ISSUE TITLE
The documentation does not clearly explain how Kepler works in detail

### ISSUE THREAD

**Issue by jonggyup** [sustainable-computing-io/kepler#933]
### Which document would you like to be mentioned?

Hi,

I feel like the documentation doesn't clearly explain how Kepler works in detail with/without RAPL available.

From my understanding, 

Kepler gathers application activities such as cache miss, CPU cycles, and average frequencies per process/container/pod/system using ebpf.

At the same time, they gather ground-truth energy from RAPL.

Afterward, Kepler divides the energy using CPU cycles, and cache misses

Am I correct? Then, what is the point of gathering per-process information when RAPL is available?

In the case when RAPL is not available, Kepler estimates the power using ML with such metrics.

Is it truly online ML? how does it work in detail?

Thank you!

### Why is this needed?

Better understanding for readers and users

**Comment by rootfs** [comment]
@jonggyup you are spot on! would you like to help improve the doc [here](https://github.com/sustainable-computing-io/kepler-doc)?
