### ISSUE TITLE
Bump up to golang 1.21

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/kepler#934]
Bump up to golang 1.21

_Originally posted by @SamYuan1990 in https://github.com/sustainable-computing-io/kepler/pull/924#discussion_r1327891431_

**Comment by kmova** [comment]
can I help with this issue?

**Comment by rootfs** [comment]
contributions are always welcome

**Comment by SamYuan1990** [comment]
currently our base image is registry.access.redhat.com/ubi9/go-toolset:1.20 @rootfs , may I know can we have registry.access.redhat.com/ubi9/go-toolset:1.21?

**Comment by SamYuan1990** [comment]
Current base image as ubi just have 1.20 golang version supported.

**Comment by dave-tucker** [comment]
Closed via https://github.com/sustainable-computing-io/kepler/pull/1404
