### ISSUE TITLE
cpu time becomes zero after long run

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#96]
**Describe the bug**
After running for extended hours, the curr_cpu_time becomes zero and never recovers
```json
{
  "__name__": "node_energy_stat",
  "container": "kepler-exporter",
  "cpu_architecture": "Cascade Lake",
  "curr_cache_misses": "10019190",
  "curr_cpu_cycles": "4005839184",
  "curr_cpu_instructions": "5068047632",
  "curr_cpu_time": "0.000000",              <----------- this never recovers
  "curr_energy_in_core": "154835.000000",
  "curr_energy_in_dram": "5.000000",
  "curr_energy_in_gpu": "0.000000",
  "curr_energy_in_other": "0.000000",
  "curr_resident_memory": "10457391104.000000",
  "endpoint": "http",
  "instance": "xxxxx",
  "job": "kepler-exporter",
  "namespace": "monitoring",
  "node_name": "xxxx",
  "pod": "kepler-exporter-9k75l",
  "service": "kepler-exporter"
}
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootfs** [comment]
cpu time is calculated [here](https://github.com/sustainable-computing-io/kepler/blob/main/pkg/collector/reader.go#L284-L290)
cc @marceloamaral

**Comment by marceloamaral** [comment]
@rootfs do we still have this problem?
