### ISSUE TITLE
for platform validation will self host owner install ebpf before the GHA been triggered?

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/kepler#962]
https://github.com/sustainable-computing-io/kepler/blob/a1b042d87a9f46e5403ec4eecebb17e2b3916402/.github/workflows/platform-validation.yml#L136

as kepler-action GHA will install ebpf(either bcc or libbpf with 0.0.2 version) hence the question here is:
for platform validation will self host owner install ebpf before the GHA been triggered?

or we should hard code a configuration here so that  kepler-action will install ebpf during process?

**Comment by jiere** [comment]
@SamYuan1990 , thanks for pointing out this, it seems that 0.0.2 GHA introduced the "ebpfprovider" env, so we may need to set it in GHA yaml properly, let me fix it soon.
