### ISSUE TITLE
Change default Prometheus scraping interval from 3s to 30s

### ISSUE THREAD

**Issue by mcalman** [sustainable-computing-io/kepler#963]
### What would you like to be added?

I recommend we change the [Prometheus scraping interval for Kepler](https://github.com/sustainable-computing-io/kepler/blob/02dc840382575f70b6dfd8b497f7afe44f858f15/manifests/config/exporter/prometheus_service_monitor.yaml#L10C6-L10C6) from 3s to 30s.

First discussed here: https://github.com/sustainable-computing-io/kepler/discussions/915#discussioncomment-7186137

### Why is this needed?

As seen in the plots below, this will reduce overhead for both Kepler and Prometheus.

30s is the default scraping interval for Prometheus and any users who needs finer granularity can change the value in the service monitor yaml. As pointed out by @marceloamaral, Kepler uses counter metrics so no accuracy should be lost with a slower scraping frequency.

![image](https://github.com/sustainable-computing-io/kepler/assets/68564154/64ef6509-e6d5-44dd-a4ff-fa6a72e1d5ec)
![image](https://github.com/sustainable-computing-io/kepler/assets/68564154/e17de72f-e0ec-4038-a640-ddc4966e5360)
![image](https://github.com/sustainable-computing-io/kepler/assets/68564154/5b15dddb-a043-4c13-a1e5-27e087a24ae2)
![image](https://github.com/sustainable-computing-io/kepler/assets/68564154/9a444a07-fa5d-4b58-8a63-415ec2f6a135)
Experiment setup:
- Single node Kind cluster
- 40 dummy containers on node
- Average overhead values when Kepler is not deployed are subtracted to get "Kepler attributed" overhead for Prometheus

### Requirements

- [ ] Change [scrape interval default value]((https://github.com/sustainable-computing-io/kepler/blob/02dc840382575f70b6dfd8b497f7afe44f858f15/manifests/config/exporter/prometheus_service_monitor.yaml#L10C6-L10C6)) to 30s
- [ ] Add documentation informing users how to change the scrape interval

**Comment by marceloamaral** [comment]
@mcalman, could you please create a PR?

Within the PR, let's include some comments in the documentation.

Btw, the only potential drawback I can think of at the moment is that there might be a delay in the appearance of metrics with the 30-second interval.
