### ISSUE TITLE
Kepler overhead management and scalability improvement

### ISSUE THREAD

**Issue by rootfs** [sustainable-computing-io/kepler#964]
To investigate Kepler exporter cpu usage and network traffic with regard to the number of pods, the bpf probe frequency, prometheus scrape frequency, the number of metrics, the format of the metrics, the prometheus client pkg. 

- [ ] https://github.com/sustainable-computing-io/kepler/issues/963

**Comment by marceloamaral** [comment]
We can update the Prometheus scrape frequency without harming the Kepler accuracy since we use counters.

But we need to be careful for any update in the interval Kepler sampling frequency since it reads gauge metrics. Larger interval results in missing data.
