### ISSUE TITLE
No metric value shown by Kepler 0.6 on VM

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/kepler#973]
### What happened?

When Kepler exporter is deployed on OpenShift VM it shows values as 0 for most of the metrics that are exported.

Below attached is a screenshot for reference:

![Screenshot 2023-10-09 at 6 08 28 PM](https://github.com/sustainable-computing-io/kepler/assets/115542213/f0263169-597a-452c-9379-e01f30dc9aa3)

### What did you expect to happen?

Kepler exporter exporting some values against the above metrics.

### How can we reproduce it (as minimally and precisely as possible)?

* Deploy Kepler(`release-0.6`) using Kepler-Operator on OpenShift VM.
* Check either OpenShift or Grafana dashboards to see whether panels updates after some time.update

### Kepler image tag

<details>
release-0.6
</details>

### Kubernetes version

<details>
OCP 4.13
</details>

### Cloud provider or bare metal

<details>
VM
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>
oc get cm kepler-exporter-cm -n openshift-kepler-operator -o yaml

```
apiVersion: v1
data:
  BIND_ADDRESS: 0.0.0.0:9103
  CGROUP_METRICS: '*'
  CPU_ARCH_OVERRIDE: ""
  ENABLE_EBPF_CGROUPID: "true"
  ENABLE_GPU: "true"
  ENABLE_PROCESS_METRICS: "false"
  ENABLE_QAT: "false"
  EXPOSE_CGROUP_METRICS: "true"
  EXPOSE_HW_COUNTER_METRICS: "true"
  EXPOSE_IRQ_COUNTER_METRICS: "true"
  EXPOSE_KUBELET_METRICS: "true"
  KEPLER_LOG_LEVEL: "1"
  KEPLER_NAMESPACE: openshift-kepler-operator
  METRIC_PATH: /metrics
  MODEL_CONFIG: CONTAINER_COMPONENTS_ESTIMATOR=false
  REDFISH_PROBE_INTERVAL_IN_SECONDS: "60"
  REDFISH_SKIP_SSL_VERIFY: "true"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-09T07:57:51Z"
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/managed-by: kepler-operator
    app.kubernetes.io/part-of: kepler
    sustainable-computing.io/app: kepler
  name: kepler-exporter-cm
  namespace: openshift-kepler-operator
  ownerReferences:
  - apiVersion: kepler.system.sustainable.computing.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Kepler
    name: kepler
    uid: abb5ac97-30f7-48fb-9d4a-0dcd102a3e36
  resourceVersion: "85309"
  uid: 028a0bda-3c65-494c-b74b-5b324f45b12d
```
oc get daemonsets.apps -n openshift-kepler-operator -o yaml

```
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "1"
    creationTimestamp: "2023-10-09T07:57:51Z"
    generation: 1
    labels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/managed-by: kepler-operator
      app.kubernetes.io/part-of: kepler
      sustainable-computing.io/app: kepler
    name: kepler-exporter-ds
    namespace: openshift-kepler-operator
    ownerReferences:
    - apiVersion: kepler.system.sustainable.computing.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Kepler
      name: kepler
      uid: abb5ac97-30f7-48fb-9d4a-0dcd102a3e36
    resourceVersion: "85311"
    uid: 7ab4bac1-ada7-4f10-9240-46c224867e94
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/managed-by: kepler-operator
        app.kubernetes.io/name: kepler-exporter
        app.kubernetes.io/part-of: kepler
        sustainable-computing.io/app: kepler
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: exporter
          app.kubernetes.io/managed-by: kepler-operator
          app.kubernetes.io/name: kepler-exporter
          app.kubernetes.io/part-of: kepler
          sustainable-computing.io/app: kepler
        name: kepler-exporter-ds
        namespace: openshift-kepler-operator
      spec:
        containers:
        - command:
          - /usr/bin/kepler
          - -address
          - 0.0.0.0:9103
          - -enable-gpu=$(ENABLE_GPU)
          - -enable-cgroup-id=true
          - -v=$(KEPLER_LOG_LEVEL)
          - -kernel-source-dir=/usr/share/kepler/kernel_sources
          - -redfish-cred-file-path=/etc/redfish/redfish.csv
          env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: KEPLER_LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                key: KEPLER_LOG_LEVEL
                name: kepler-exporter-cm
          - name: ENABLE_GPU
            valueFrom:
              configMapKeyRef:
                key: ENABLE_GPU
                name: kepler-exporter-cm
          image: quay.io/sustainable_computing_io/kepler:release-0.6
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 9103
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
          name: kepler-exporter
          ports:
          - containerPort: 9103
            name: http
            protocol: TCP
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /lib/modules
            name: lib-modules
            readOnly: true
          - mountPath: /sys
            name: tracing
            readOnly: true
          - mountPath: /usr/src/kernels
            name: kernel-src
            readOnly: true
          - mountPath: /sys/kernel/debug
            name: kernel-debug
          - mountPath: /proc
            name: proc
          - mountPath: /etc/kepler/kepler.config
            name: cfm
        dnsPolicy: ClusterFirstWithHostNet
        hostPID: true
        nodeSelector:
          kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: kepler-exporter-sa
        serviceAccountName: kepler-exporter-sa
        terminationGracePeriodSeconds: 30
        tolerations:
        - operator: Exists
        volumes:
        - hostPath:
            path: /lib/modules
            type: ""
          name: lib-modules
        - hostPath:
            path: /sys
            type: ""
          name: tracing
        - hostPath:
            path: /proc
            type: ""
          name: proc
        - hostPath:
            path: /usr/src/kernels
            type: ""
          name: kernel-src
        - hostPath:
            path: /sys/kernel/debug
            type: ""
          name: kernel-debug
        - configMap:
            defaultMode: 420
            name: kepler-exporter-cm
          name: cfm
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
  status:
    currentNumberScheduled: 17
    desiredNumberScheduled: 17
    numberAvailable: 17
    numberMisscheduled: 0
    numberReady: 17
    observedGeneration: 1
    updatedNumberScheduled: 17
kind: List
metadata:
  resourceVersion: ""
```
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by rootfs** [comment]
similar to #959

**Comment by marceloamaral** [comment]
@vprashar2929 can you check if the problem was fixed?

**Comment by vprashar2929** [comment]
Sure will test with the latest Kepler Image

**Comment by rootfs** [comment]
thank you @vprashar2929 

if it works well, please update the issue, so @husky-parul can create a 0.6.1 release, thanks

**Comment by vprashar2929** [comment]
@rootfs @marceloamaral  I deployed the latest Kepler image on OpenShift VM and I was able to see the values for metrics but I tried to make a comparison between `release-0.5.5` and the `latest`. I observed that there was a big difference in terms of readings which we get from both releases.

To further explain I conducted two experiments:
* Deploying Kepler with `release-0.5.5` and `latest` on two different OpenShift VM clusters. After letting the cluster run for more than an hour I observed that there was a big difference in terms of value which we get from metrics on both versions. Attached screenshot of the Grafana dashboard for reference.

Kepler running with `release-0.5.5`

![Screenshot 2023-10-11 at 4 22 19 PM](https://github.com/sustainable-computing-io/kepler/assets/115542213/22e6bf19-35be-44cd-ac77-e56662c2b0de)


![Screenshot 2023-10-11 at 4 15 53 PM](https://github.com/sustainable-computing-io/kepler/assets/115542213/f5a34031-e599-458c-8a21-ca3e62ff7825)


Kepler running with `latest`

![Screenshot 2023-10-11 at 4 10 53 PM](https://github.com/sustainable-computing-io/kepler/assets/115542213/2b46fee8-ef6b-4cfa-98cf-c302b1c73c89)

![Screenshot 2023-10-11 at 4 15 45 PM](https://github.com/sustainable-computing-io/kepler/assets/115542213/7fafa40c-93c8-4e55-9255-3474a99defa2)



* Next I deployed both versions of Kepler on the same OpenShift VM cluster and there also I was able to see the difference in the metric value from both releases.

![Screenshot 2023-10-11 at 4 05 23 PM](https://github.com/sustainable-computing-io/kepler/assets/115542213/5a440256-efc5-41eb-96f1-7fa7a168c11c)

Here Kepler with `release-0.5.5` is deployed inside `openshift-kepler-operator` namespace and `latest` is deployed on `openshift-kepler-operator-x` namespace

 
Is there any significant change related to pre-trainined model that went into `release-0.6` which is not present in `release-0.5.5` due to which there is a difference between the two releases

**Comment by rootfs** [comment]
cc @marceloamaral @sunya-ch 

@vprashar2929 can you check if idle power (e.g. `mode="idle"` in the `kepler_container_joules_total` metric) is there on 0.5.5? In 0.6, the idle power metric is turned off by default.

**Comment by vprashar2929** [comment]
No, I cannot see idle power in `kepler_container_joules_total` metric in 0.5.5.

<img width="1512" alt="Screenshot 2023-10-11 at 6 59 26 PM" src="https://github.com/sustainable-computing-io/kepler/assets/115542213/2b468f76-f2e8-4e22-95be-a30462056b23">

**Comment by sunya-ch** [comment]
> @vprashar2929 are the dashboard queries the same? We have update the dashboard, it is worth checking just in case....
> 
> Also, in your last figure, can you apply `irate`, it will be easier to compare the scenarios.
> 
> Can you also show the bpf cpu time?
> 
> @sunya-ch did the trained model changed? I mean, trained with new data?

Before release v0.6, there are multiple bugs/missing logics on both core kepler and kepler-model-server. 
The big bug is on the model server that does not divide power label with sampling period (fixed by  https://github.com/sustainable-computing-io/kepler-model-server/pull/172). 
With only that bug, the model is labeled with 3-times power.

**Comment by vprashar2929** [comment]
> are the dashboard queries the same?
We have update the dashboard, it is worth checking just in case

Yes, we are using the latest promql queries in our dashboards.

> Also, in your last figure, can you apply irate, it will be easier to compare the scenarios.

Here is the screenshot with `irate`

<img width="1512" alt="Screenshot 2023-10-12 at 12 07 56 AM" src="https://github.com/sustainable-computing-io/kepler/assets/115542213/5ed97c0c-9a08-44fd-aa8a-7bcb8010dfdb">

> Can you also show the bpf cpu time?

Do you mean this?

<img width="1512" alt="Screenshot 2023-10-12 at 12 12 34 AM" src="https://github.com/sustainable-computing-io/kepler/assets/115542213/e782a397-9a7f-4c51-aa00-6499a4c05fbd">

**Comment by rootfs** [comment]
thank @vprashar2929 for setting up two clusters: a 6 node baremetal (Cypress Cove CPU) one and a 6 node VM (Skylake CPU) one.

On the BM:
![image](https://github.com/sustainable-computing-io/kepler/assets/7062400/90700a1e-fc39-42b1-861b-21b87d10e015)

On the VM:
![image](https://github.com/sustainable-computing-io/kepler/assets/7062400/efedce0d-f820-4909-beda-2c72c82ccf04)

**Comment by rootfs** [comment]
The BM and VM dynamic energy metrics are very similar, I believe the 0.6 release model is working very well.
 
wdyt @sunya-ch @marceloamaral

**Comment by sthaha** [comment]
It would be great if we could implement this idea of comparing `vm` to `bm` in our CI (no shortage of acronyms here :D) 
vm -> Virtual Machine 
bm -> Bare Metal 

I have updated https://github.com/sustainable-computing-io/kepler/issues/980 to reflect this

**Comment by rootfs** [comment]
Also have a comparison of idle power. Idle power metrics is automatically turned on for BM. It needs to be explicitly turned on for VM based on the assumption the underlying physical server's idle power can be attributed to the VM completely.

### BM
![image](https://github.com/sustainable-computing-io/kepler/assets/7062400/77d980f2-1049-43f8-89a6-081bb0755e3f)

### VM
![image](https://github.com/sustainable-computing-io/kepler/assets/7062400/2f767974-6b82-46fe-9139-ae3a1098e8b0)

**Comment by rootfs** [comment]
@sthaha would you please make the cli option `-expose-estimated-idle-power=true` available in the operator

**Comment by sthaha** [comment]
@rootfs Is that a one off deployment or a permanent change to https://github.com/sustainable-computing-io/kepler-operator/blob/d094ded0192f4583db2aeee73a0eebefc7707b4a/pkg/components/exporter/exporter.go#L140 ?

**Comment by sthaha** [comment]
@rootfs  On a related note, of 0.6.x, should [`-enable-cgroup-id=true`](https://github.com/sustainable-computing-io/kepler-operator/blob/d094ded0192f4583db2aeee73a0eebefc7707b4a/pkg/components/exporter/exporter.go#L141C6-L141C6) be `false` ?

**Comment by sthaha** [comment]
@rootfs https://github.com/sustainable-computing-io/kepler-operator/pull/270/files 🙏

**Comment by marceloamaral** [comment]
> would you please make the cli option -expose-estimated-idle-power=true available in the operator

This parameter can be potentially dangerous and may lead to misunderstandings. The 'idle' value refers to the total host idle power, which is not distributed among all the running VMs on the node. Consequently, each VM may wrongly double-count the host's idle time if there are multiple VMs on the same host. However, in public cloud environments, it is impractical to determine the number of running VMs on a node.

This parameter is intended for use on bare metal servers that rely on node power estimation because they do not provide real-time power metrics, or when there is only one VM running on the host for very specific scenarios.

**Comment by marceloamaral** [comment]
So, the idle power for VMs should be disabled by default, and can be enabled in some specific scenarios...

**Comment by sthaha** [comment]
@marceloamaral, could you please help me understand what you meant by ... 

> can be enabled in some specific scenarios... 

What are the specific scenarious? Do you mean when the user is sure that only 1 VM is running on host? 

> we should carefully describe the parameter

Could you please expand further? Do you mean provide option like below to enable this option through kepler spec so that users who are sure about the cluster setup can enable it? 

```
spec:
  estimator:  # NOTE: estimator instead of exporter
      idlePower: 
         enabled: true
```
  
For now I will revert `enabling` by default, until this is clarified.

**Comment by marceloamaral** [comment]
> What are the specific scenarios? Do you mean when the user is sure that only 1 VM is running on host?

Yes, idle power should not be exposed for VMs because it's impossible to split the host's idle power among all the running VMs due to the lack of information regarding the number of VMs on the host.

Idle power should only be exposed in cases where power estimation is employed on bare metal servers (BMs) or when there's just one VM on the node. This scenario can happen when a user allocates a single, exceptionally large VM that takes all the available host resources.

We need to be very careful with the estimated idle power to do not provide unrealistic results.
